// Pure shared rules. The browser copy is generated by scripts/build-meetup-timing.mjs.
export type FestivalSet = {id:string;artist:string;day:string;festivalDate:string;stage:string;start:string;end:string};
export type TimingChoice = {mode:string;setId:string;nextSetId?:string;minutes?:number};
const stamp = (value:string) => Date.parse(value + "Z"); // festival wall-clock arithmetic, not device time
export function resolveMeetupTiming(input:TimingChoice, sets:readonly FestivalSet[]) {
  if (!input || !["before","after","between"].includes(input.mode)) throw new Error("Choose before, after, or between sets.");
  const first=sets.find(set=>set.id===input.setId);
  if (!first) throw new Error("Choose a set from this festival’s lineup.");
  const minutes=input.minutes;
  if (typeof minutes!=="number" || !Number.isInteger(minutes) || minutes<0 || minutes>120) throw new Error("Choose an offset from 0 to 120 minutes.");
  const snapshot=(set:FestivalSet)=>({id:set.id,artist:set.artist,day:set.day,festivalDate:set.festivalDate,stage:set.stage,start:set.start,end:set.end});
  let time:number, label:string, next:FestivalSet|undefined;
  if(input.mode==="between"){
    next=sets.find(set=>set.id===input.nextSetId);
    if(!next || next.id===first.id || next.festivalDate!==first.festivalDate) throw new Error("Choose two different sets on the same festival day.");
    const gap=(stamp(next.start)-stamp(first.end))/60000;
    if(gap<0) throw new Error("Those sets overlap or are in reverse order. Choose a later second set.");
    if(minutes>gap) throw new Error("That meetup time is after the second set starts. Choose a smaller offset.");
    time=stamp(first.end)+minutes*60000;
    label=`Between ${first.artist} and ${next.artist}`;
  }else{
    time=stamp(input.mode==="before"?first.start:first.end)+(input.mode==="before"?-1:1)*minutes*60000;
    label=minutes ? `${minutes} min ${input.mode} ${first.artist}` : `At ${first.artist}’s ${input.mode==="before"?"start":"end"}`;
  }
  if(!Number.isFinite(time))throw new Error("This set is missing its scheduled time.");
  const when=new Date(time).toISOString().slice(0,16);
  return {when,timing:{mode:input.mode,setId:first.id,...(next?{nextSetId:next.id}:{}),minutes,label,sets:[snapshot(first),...(next?[snapshot(next)]:[])]}};
}

export function availableNextSets(firstId:string,sets:readonly FestivalSet[]) {
  const first=sets.find(set=>set.id===firstId);
  return first?sets.filter(set=>set.id!==first.id&&set.festivalDate===first.festivalDate&&stamp(set.start)>=stamp(first.end)):[];
}
