const {test,before}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const path=require('node:path');const esbuild=require('esbuild');let api;
const token='a'.repeat(43),otherToken='b'.repeat(43);
before(async()=>{const result=await esbuild.build({entryPoints:[path.join(__dirname,'../../../../convex/statements.ts')],bundle:true,write:false,platform:'node',format:'cjs',plugins:[{name:'test',setup(build){build.onResolve({filter:/\.\/_generated\/server$/},()=>({path:'server',namespace:'test'}));build.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const query=x=>x, mutation=x=>x, internalQuery=x=>x, internalMutation=x=>x;'}));}}]});const module={exports:{}};vm.runInNewContext(result.outputFiles[0].text,{module,exports:module.exports,require,process:{env:{CARD_PAYMENTS_WORKSPACE_OWNER:'owner',CARD_PAYMENTS_ALLOWED_EMAIL:'owner@example.com'}},console,TextEncoder,TextDecoder});api=module.exports;});
function fixture(identity=null){const tables={paymentStatements:[{_id:'s1',owner:'owner',token,enabled:true,title:'Sample',period:'Sample period',dueDate:'2026-10-12',balanceCents:7000,storageId:'private-file',fingerprint:'old'},{_id:'s2',owner:'other',token:otherToken,enabled:true}],paymentStatementRows:[{_id:'r1',statementId:'s1',date:'2026-09-01',description:'Test merchant',kind:'purchase',page:1,order:0,amountCents:10000,version:0,note:''},{_id:'r2',statementId:'s1',date:'2026-09-02',description:'Test refund',kind:'credit',page:2,order:1,amountCents:-3000,version:0,note:''},{_id:'r3',statementId:'s2',amountCents:5000,version:0,note:''}]};let seq=0;const ctx={auth:{getUserIdentity:async()=>identity},db:{system:{get:async()=>({contentType:'application/pdf',size:500})},query(table){const filters=[];const q={eq(k,v){filters.push(r=>r[k]===v);return q;}};const b={withIndex(_,fn){fn(q);return b;},async collect(){return tables[table].filter(r=>filters.every(f=>f(r)));},async unique(){const rows=await b.collect();assert.ok(rows.length<=1);return rows[0]||null;}};return b;},async get(id){return Object.values(tables).flat().find(r=>r._id===id)||null;},async patch(id,data){const row=await ctx.db.get(id);for(const[k,v]of Object.entries(data)){if(v===undefined)delete row[k];else row[k]=v;}},async insert(table,data){const id='new'+(++seq);tables[table].push({_id:id,...data});return id;}}};return {tables,ctx,run:(name,args={})=>api[name].handler(ctx,args)};}
const assign={token,id:'r1',expectedVersion:0,allocation:{parents:10000,john:0,other:0},note:''};
test('token grants only the selected statement; response omits secrets, owner and storage',async()=>{const f=fixture(),result=await f.run('review',{token});assert.equal(result.rows.length,2);for(const key of ['owner','token','storageId','fingerprint'])assert.equal(result[key],undefined);assert.equal(result.rows[0].statementId,undefined);assert.equal(await f.run('file',{token}),'private-file');await assert.rejects(f.run('save',{...assign,id:'r3'}),/Charge not found/);});
test('missing, guessed and revoked links cannot read, write or fetch PDFs',async()=>{for(const bad of ['', 'a'.repeat(42),'z'.repeat(43)]){const f=fixture();for(const fn of ['review','file'])await assert.rejects(f.run(fn,{token:bad}),/unavailable/);await assert.rejects(f.run('save',{...assign,token:bad}),/unavailable/);}const f=fixture();f.tables.paymentStatements[0].enabled=false;for(const fn of ['review','file'])await assert.rejects(f.run(fn,{token}),/unavailable/);await assert.rejects(f.run('save',assign),/unavailable/);});
test('amounts use exact cents; splits reject fractions, wrong sums and mixed signs',async()=>{for(const allocation of [{parents:9000,john:0,other:0},{parents:9999.5,john:.5,other:0},{parents:11000,john:-1000,other:0}])await assert.rejects(fixture().run('save',{...assign,allocation}),/split must/);const f=fixture();await f.run('save',{...assign,allocation:{parents:5001,john:4999,other:0}});assert.equal(f.tables.paymentStatementRows[0].allocation.parents,5001);await f.run('save',{...assign,id:'r2',allocation:{parents:-3000,john:0,other:0}});await assert.rejects(fixture().run('save',{...assign,id:'r2',allocation:{parents:3000,john:-6000,other:0}}),/split must/);});
test('stale saves cannot overwrite another reviewer; clear and notes preserve consistency',async()=>{const f=fixture();await f.run('save',assign);await assert.rejects(f.run('save',assign),/changed on another device/);await f.run('save',{...assign,expectedVersion:1,allocation:null,note:' ask later '});const r=f.tables.paymentStatementRows[0];assert.equal(r.allocation,undefined);assert.equal(r.note,'ask later');assert.equal(r.version,2);});
test('library and revocation require owner login and ownership',async()=>{for(const name of ['list','revoke'])await assert.rejects(fixture().run(name,{id:'s1'}),/not authorized/);const f=fixture({email:'owner@example.com',emailVerified:true});assert.equal((await f.run('list')).length,1);await assert.rejects(f.run('revoke',{id:'s2'}),/not found/);await f.run('revoke',{id:'s1'});await assert.rejects(f.run('review',{token}),/unavailable/);});
test('import rejects unreconciled or duplicate statements; fresh rows stay unassigned',async()=>{const input={token:'c'.repeat(43),title:'Test',period:'Test period',dueDate:'2026-10-12',balanceCents:100,fingerprint:'f'.repeat(64),storageId:'pdf',rows:[{date:'2026-09-01',description:'Example',amountCents:100,kind:'purchase',page:1}]};await assert.rejects(fixture().run('importStatement',{...input,balanceCents:101}),/reconcile/);const f=fixture();const id=await f.run('importStatement',input);assert.equal(f.tables.paymentStatementRows.find(r=>r.statementId===id).allocation,undefined);await assert.rejects(f.run('importStatement',input),/already imported/);});
