/* Monthly utility sheet; service dates retain the statement's actual billing cycle. */
window.RentBillSheet = function ({root,save,refresh,canEdit,openFiles}) {
  const make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  const button=(label,fn,cls='quiet')=>{const b=make('button',label,cls);b.type='button';b.onclick=fn;return b;};
  const fields=['statementDate','periodStart','periodEnd','dueDate','chargesCents','previousCents','paymentsCents'];
  const labels=['Statement date','Service start','Service end','Due date','New charges','Prior balance / credit','Payments reported'];
  const cash=n=>(n/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
  let bills=[],files=[],drafts=new Map(),year=new Date().getFullYear(),pending=false,locked=false,attempt=null,generation=0,body,status,error,saveButton,undoButton,yearLabel,rows=[];
  function cents(text){const s=text.trim().replace(/[$,]/g,'');if(!s)return 0;if(!/^-?\d+(\.\d{0,2})?$/.test(s))throw Error('Use dollar amounts with up to two decimal places.');const n=Math.round(Number(s)*100);if(!Number.isSafeInteger(n)||Math.abs(n)>100000000)throw Error('Enter a valid amount.');return n;}
  function validateDate(s){if(!/^20\d{2}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)throw Error('Enter dates as YYYY-MM-DD.');}
  const original=(r,f)=>r.bill?(f.endsWith('Cents')?(r.bill[f]/100).toFixed(2):r.bill[f]):'';
  function values(r,strict=false){const value={};fields.forEach(f=>{const s=drafts.get(r.key)?.[f]??original(r,f);value[f]=f.endsWith('Cents')?cents(s):s;});value.totalCents=value.previousCents-value.paymentsCents+value.chargesCents;
    if(strict){fields.slice(0,4).forEach(f=>validateDate(value[f]));if(value.statementDate.slice(0,7)!==r.month)throw Error('Statement date must be in '+r.month+'.');if(value.periodStart>value.periodEnd||value.dueDate<value.statementDate||value.paymentsCents<0)throw Error('Check the service dates, due date, and payments.');}
    return value;
  }
  function mark(r,f,v){const d={...(drafts.get(r.key)||{})};let same=v===original(r,f);if(f.endsWith('Cents')){try{same=cents(v)===cents(original(r,f));}catch{}}if(same)delete d[f];else d[f]=v;if(Object.keys(d).length)drafts.set(r.key,d);else drafts.delete(r.key);}
  function state(){const count=drafts.size;status.textContent=pending?'Saving statements…':count?`${count} statement${count===1?'':'s'} edited`:'All changes saved';saveButton.disabled=!count||pending||locked;undoButton.disabled=!count||pending||locked||!!attempt;root.querySelectorAll('.bill-cell').forEach(i=>{i.readOnly=pending||locked||!!attempt;i.classList.toggle('edited',drafts.get(i.dataset.key)?.[i.dataset.field]!==undefined);});root.querySelectorAll('.bill-document').forEach(b=>b.disabled=pending||locked||count>0||!!b.dataset.empty);}
  function totals(r){const tr=[...body.rows].find(tr=>tr.dataset.key===r.key);try{tr.querySelector('.bill-total').textContent=r.bill||drafts.has(r.key)?cash(values(r).totalCents):'—';tr.classList.remove('invalid-row');}catch{tr.querySelector('.bill-total').textContent='Check amount';tr.classList.add('invalid-row');}}
  function showError(s){error.textContent=s;error.hidden=!s;}
  function renderRows(){yearLabel.textContent=String(year);body.replaceChildren();rows=[];
    for(let m=1;m<=12;m++){const month=`${year}-${String(m).padStart(2,'0')}`,saved=bills.filter(b=>b.month===month).sort((a,b)=>a.statementDate.localeCompare(b.statementDate));for(const bill of saved.length?saved:[null])rows.push({key:bill?bill._id:month,month,bill});}
    rows.forEach((r,rowIndex)=>{const tr=make('tr');tr.dataset.key=r.key;tr.dataset.month=r.month;const th=make('th',new Date(r.month+'-15T12:00:00').toLocaleDateString('en-US',{month:'short'}));th.scope='row';if(!r.bill)th.append(make('span','new','new-month'));tr.append(th);
      fields.forEach((field,i)=>{const td=make('td'),input=make('input',undefined,'bill-cell');input.type='text';input.inputMode=i<4?'text':'decimal';input.autocomplete='off';input.spellcheck=false;input.value=drafts.get(r.key)?.[field]??original(r,field);input.placeholder=i<4?'YYYY-MM-DD':'—';input.dataset.key=r.key;input.dataset.field=field;input.setAttribute('aria-label',`${r.month} ${labels[i]}`);input.onfocus=()=>input.select();
        input.oninput=()=>{if(!canEdit()){input.value=drafts.get(r.key)?.[field]??original(r,field);return;}mark(r,field,input.value);showError('');totals(r);state();};
        input.onblur=()=>{if(i>=4&&input.value.trim()){try{input.value=(cents(input.value)/100).toFixed(2);}catch{}}};
        input.onkeydown=e=>{if(['Tab','Enter','ArrowDown','ArrowUp'].includes(e.key)){const cells=[...root.querySelectorAll('.bill-cell')];let target;if(e.key==='Tab')target=cells[cells.indexOf(input)+(e.shiftKey?-1:1)];else target=body.rows[rowIndex+((e.key==='ArrowUp'||e.shiftKey)?-1:1)]?.querySelector(`[data-field="${field}"]`);if(target){e.preventDefault();target.focus();}}
          if(e.key==='Escape'&&!attempt){const d=drafts.get(r.key);if(d){delete d[field];if(!Object.keys(d).length)drafts.delete(r.key);}input.value=original(r,field);totals(r);state();}};
        input.onpaste=e=>{const text=e.clipboardData.getData('text');if(!/[\t\n]/.test(text))return;e.preventDefault();if(pending||attempt||!canEdit())return;try{const matrix=text.replace(/\r/g,'').replace(/\n$/,'').split('\n').map(s=>s.split('\t'));if(rowIndex+matrix.length>rows.length||matrix.some(a=>i+a.length>fields.length))throw Error('Paste must fit within the editable cells for this year.');const changes=[];matrix.forEach((a,dy)=>a.forEach((v,dx)=>{if(i+dx>=4)cents(v);else if(v)validateDate(v);changes.push({r:rows[rowIndex+dy],f:fields[i+dx],v});}));for(const c of changes){mark(c.r,c.f,c.v);body.querySelector(`[data-key="${c.r.key}"][data-field="${c.f}"]`).value=c.v;totals(c.r);}showError('');state();}catch(e){showError(e.message);}};
        td.append(input);tr.append(td);
      });
      tr.append(make('td','—','bill-total computed'));const attachment=make('td');const count=files.filter(f=>r.bill&&f.billId===r.bill._id).length;const proof=button(count?`▤ ${count} PDF${count===1?'':'s'}`:'+ PDF',()=>{if(!canEdit())return;if(drafts.size){showError('Save or discard the statement edits first.');return;}openFiles(r.bill);},'bill-document cell-document');proof.disabled=!r.bill;proof.title=r.bill?'Open this statement and its PDFs':'Enter and save the statement before attaching a PDF';attachment.append(proof);if(!r.bill)proof.dataset.empty='true';tr.append(attachment);body.append(tr);totals(r);
    });state();root.querySelectorAll('[data-empty]').forEach(b=>b.disabled=true);
  }
  async function commit(){if(pending||locked||!drafts.size||!canEdit())return;const g=generation;try{
    if(!attempt){if(drafts.size>24)throw Error('Save up to 24 statements at a time.');const all=[];for(const [key] of drafts){const bill=bills.find(b=>b._id===key),r={key,month:bill?.month||key,bill};all.push({...values(r,true),month:r.month,note:bill?.note||'',expectedVersion:bill?.version||0,...(bill?{id:bill._id}:{})});}attempt={rows:all,requestKey:crypto.randomUUID()};}
    pending=true;state();showError('');await save(attempt);if(g!==generation)return;drafts.clear();attempt=null;pending=false;await refresh();
  }catch(e){if(g===generation){if(/another device|already logged/.test(e.message))attempt=null;showError((e.message||'Couldn’t save.')+(attempt?' Your changes are preserved; Save statements retries the same values.':''));}}
  finally{if(g===generation){pending=false;state();}}}
  function mount(){root.replaceChildren();const panel=make('section',undefined,'sheet-panel utility-ledger'),toolbar=make('div',undefined,'sheet-toolbar'),title=make('div');title.append(make('h2','PG&E monthly ledger'),make('p','One row per statement month. Type or paste into cells; open the PDF from its row.'));
    const nav=make('div',undefined,'sheet-year');yearLabel=make('strong',String(year));const prev=button('←',()=>{if(year>2000){year--;renderRows();}}),next=button('→',()=>{if(year<2099){year++;renderRows();}});prev.setAttribute('aria-label','Previous utility year');next.setAttribute('aria-label','Next utility year');nav.append(prev,yearLabel,next);toolbar.append(title,nav);panel.append(toolbar);
    const wrap=make('div',undefined,'sheet-scroll');wrap.tabIndex=0;wrap.setAttribute('aria-label','Editable PG&E ledger; scroll horizontally for all columns');const table=make('table',undefined,'sheet-table utility-table'),cols=make('colgroup');[84,132,132,132,132,110,126,125,114,100].forEach(width=>{const col=make('col');col.style.width=width+'px';cols.append(col);});const head=make('thead'),groups=make('tr');for(const [text,count] of [['',1],['STATEMENT & SERVICE DATES',4],['STATEMENT AMOUNTS',3],['CALCULATED',1],['SOURCE',1]]){const th=make('th',text);th.colSpan=count;groups.append(th);}const headers=make('tr');['Month',...labels,'Total due / credit','PDF'].forEach(text=>{const th=make('th',text);th.scope='col';headers.append(th);});head.append(groups,headers);body=make('tbody');table.append(cols,head,body);wrap.append(table);panel.append(wrap);
    const foot=make('div',undefined,'sheet-footer');foot.append(make('span','Actual service dates can cross months. Total = prior balance − payments reported + new charges. Missing statements stay blank.'));const actions=make('div',undefined,'sheet-actions');status=make('span');status.setAttribute('role','status');undoButton=button('Discard edits',async()=>{drafts.clear();attempt=null;showError('');renderRows();await refresh();});saveButton=button('Save statements',commit,'primary');actions.append(status,undoButton,saveButton);foot.append(actions);panel.append(foot);error=make('p','','sheet-error');error.hidden=true;error.setAttribute('role','alert');panel.append(error);root.append(panel);renderRows();}
  mount();return {load(value){if(pending||drafts.size)return;bills=value.bills;files=value.files;renderRows();},hasChanges:()=>pending||drafts.size>0,setLocked(value){locked=value;state();},clear(){generation++;bills=[];files=[];drafts.clear();pending=false;attempt=null;mount();},};
};
