/* Private payment evidence and statement-date utility log. */
window.RentRecords = function ({root,call,fileRequest,refresh,canEdit}) {
  const make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  const cash=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
  const date=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
  const month=d=>new Date(d+'-15T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'});
  const button=(label,fn,cls='outline')=>{const b=make('button',label,cls);b.type='button';b.onclick=fn;return b;};
  let data={bills:[],files:[]},ledger={months:[],payments:[]},generation=0,pending=false,draft=false,urls=[];
  const dialog=make('dialog',undefined,'record-dialog');dialog.setAttribute('aria-label','Rent documents');document.body.append(dialog);
  function revoke(){urls.forEach(u=>URL.revokeObjectURL(u));urls=[];}
  function close(){if(pending)return;dialog.close();dialog.replaceChildren();draft=false;revoke();}
  dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
  function open(title){if(!canEdit())return false;revoke();dialog.replaceChildren();const heading=make('div',undefined,'dialog-heading');heading.append(make('h2',title),button('Close',close,'quiet'));dialog.append(heading);dialog.showModal();return true;}
  async function preview(f){if(!open(f.name))return;const g=generation,msg=make('p','Loading private file…');dialog.append(msg);try{const blob=await fileRequest('GET',{id:f._id});if(g!==generation||!dialog.open)return;const url=URL.createObjectURL(blob);urls.push(url);msg.remove();const a=make('a','Download original');a.href=url;a.download=f.name;dialog.append(a);if(f.type==='application/pdf'){const frame=make('iframe');frame.title=f.name;frame.src=url;frame.className='document-preview';dialog.append(frame);}else{const img=make('img');img.alt=f.name;img.src=url;img.className='proof-preview';dialog.append(img);}}catch(e){if(g===generation)msg.textContent='Couldn’t load the file. Close and try again.';}}
  function upload(target,title){if(!open(title))return;
    const form=make('form'),label=make('label','Choose screenshot or PDF'),input=make('input'),local=make('div'),error=make('p','','form-error');input.type='file';input.accept='image/png,image/jpeg,image/webp,application/pdf';input.id='rent-upload';label.htmlFor=input.id;input.required=true;
    const submit=make('button','Save attachment','primary');submit.type='submit';let key=crypto.randomUUID(),selected=null;
    input.onchange=()=>{selected=input.files[0];key=crypto.randomUUID();draft=!!selected;revoke();local.replaceChildren();if(selected?.type.startsWith('image/')){const img=make('img');const url=URL.createObjectURL(selected);urls.push(url);img.src=url;img.alt='Attachment preview';img.className='proof-preview';local.append(img);}else if(selected)local.append(make('p',selected.name));};
    form.append(label,input,local,make('p','Attaching a file does not change payment totals or mark a receipt checked.','muted'),error,submit);dialog.append(form);
    form.onsubmit=async e=>{e.preventDefault();if(pending||!selected)return;const g=generation;pending=true;input.disabled=submit.disabled=true;error.textContent='Uploading…';try{await fileRequest('POST',target,selected,key);if(g!==generation)return;pending=false;draft=false;close();await refresh();}catch(e){if(g===generation)error.textContent=e.message+' Your file is kept here for retry.';}finally{if(g===generation){pending=false;input.disabled=submit.disabled=false;}}};
  }
  function paymentControls(p){const wrap=make('div',undefined,'payment-proof-actions');if(!p.voidedAt){const label=make('label',undefined,'check proof-check'),input=make('input');input.type='checkbox';input.checked=!!p.checked;input.setAttribute('aria-label','Payment checked');label.append(input,make('span',p.checked?'✓ Checked':'Check payment'));if(p.checked)label.title=`Checked by ${p.checkedBy||'a workspace member'}`;
    input.onchange=async()=>{if(pending||!canEdit()){input.checked=!!p.checked;return;}const g=generation;pending=true;input.disabled=true;try{await call('mutation','setConfirmation',{id:p._id,checked:input.checked});if(g!==generation)return;pending=false;await refresh();}catch(e){if(g===generation){input.checked=!!p.checked;const err=make('span','Couldn’t save check. Try again.','form-error');wrap.append(err);}}finally{if(g===generation){pending=false;input.disabled=false;}}};wrap.append(label,button('+ Attach proof',()=>upload({paymentId:p._id},'Attach payment proof'),'quiet'));
    }
    data.files.filter(f=>f.paymentIds.includes(p._id)).forEach(f=>wrap.append(button('↗ '+f.name,()=>preview(f),'file-link')));return wrap;
  }
  function linkProof(f){if(!open('Link screenshot to a payment'))return;const form=make('form'),label=make('label','Payment'),select=make('select'),error=make('p','','form-error'),save=make('button','Link payment','primary');select.id='proof-payment';label.htmlFor=select.id;select.setAttribute('aria-label','Payment to link');save.type='submit';
    const candidates=ledger.payments.filter(p=>!p.voidedAt&&!f.paymentIds.includes(p._id)).sort((a,b)=>b.month.localeCompare(a.month));
    for(const p of candidates){const name=ledger.months.find(m=>m.month===p.month)?.config.people[p.payer]?.name||(p.payer===3?'Affil':'Resident');const o=make('option',`${month(p.month)} · ${name} · ${cash(p.amountCents)} · ${p.date}`);o.value=p._id;select.append(o);}
    form.append(label,select,make('p','You can link the same screenshot to several receipts. Check each payment separately after reviewing the proof.','muted'),error,save);dialog.append(form);SearchableSelect.enhance(select);save.disabled=!candidates.length;
    form.onsubmit=async e=>{e.preventDefault();if(pending)return;const g=generation;pending=true;save.disabled=true;try{await call('mutation','linkFile',{id:f._id,paymentId:select.value});if(g!==generation)return;pending=false;close();await refresh();}catch(e){if(g===generation)error.textContent='Couldn’t link the file. Try again.';}finally{if(g===generation){pending=false;save.disabled=false;}}};
  }
  function billForm(){if(!open('Add a PG&E statement'))return;const form=make('form'),grid=make('div',undefined,'bill-form-grid'),inputs={};
    for(const [key,label,type] of [['statementDate','Statement date','date'],['periodStart','Service starts','date'],['periodEnd','Service ends','date'],['dueDate','Due date','date'],['chargesCents','New charges ($)','number'],['previousCents','Previous balance / credit ($)','number'],['paymentsCents','Payments on statement ($)','number'],['totalCents','Statement total due / credit ($)','number']]){const wrap=make('div'),l=make('label',label),i=make('input');i.id='bill-'+key;l.htmlFor=i.id;i.type=type;i.required=true;if(type==='number')i.step='0.01';if(key==='paymentsCents')i.min=0;inputs[key]=i;wrap.append(l,i);grid.append(wrap);}
    const note=make('textarea'),nl=make('label','Notes'),file=make('input'),fl=make('label','Statement PDF (optional)'),error=make('p','','form-error'),save=make('button','Save statement','primary');note.id='bill-note';nl.htmlFor=note.id;note.maxLength=4000;file.id='bill-file';file.type='file';file.accept='application/pdf';fl.htmlFor=file.id;save.type='submit';
    form.append(make('p','Organized by statement month. Keep the actual service dates, even when they cross months. Payments are copied from the statement, not inferred from its due date.','muted'),grid,nl,note,fl,file,error,save);dialog.append(form);form.oninput=()=>draft=true;let attempt=null,billId=null;
    form.onsubmit=async e=>{e.preventDefault();if(pending)return;const g=generation;try{
      if(!attempt){const fields={note:note.value,requestKey:crypto.randomUUID()};for(const [key,input] of Object.entries(inputs)){if(key.endsWith('Cents')){if(!/^-?\d+(\.\d{1,2})?$/.test(input.value))throw Error('Use amounts with at most two decimal places.');fields[key]=Math.round(Number(input.value)*100);}else fields[key]=input.value;}attempt={fields,file:file.files[0],fileKey:crypto.randomUUID()};}
      pending=true;form.querySelectorAll('input,textarea,button').forEach(n=>n.disabled=true);error.textContent='Saving…';billId ||= await call('mutation','saveBill',attempt.fields);if(g!==generation)return;
      if(attempt.file)await fileRequest('POST',{billId},attempt.file,attempt.fileKey);if(g!==generation)return;pending=false;draft=false;close();await refresh();
    }catch(e){if(g===generation){error.textContent=e.message+(billId?' Statement saved; retry to attach the PDF.':'');if(/Enter|Check the bill|Previous balance|already logged|valid amount/.test(e.message)&&!billId)attempt=null;}}
    finally{if(g===generation){pending=false;save.disabled=false;if(!attempt)form.querySelectorAll('input,textarea').forEach(n=>n.disabled=false);}}};
  }
  function render(){root.replaceChildren();const panel=make('section',undefined,'panel utilities'),heading=make('div',undefined,'section-heading'),intro=make('div');intro.append(make('div','UTILITIES','eyebrow'),make('h2','PG&E statements'),make('p','Grouped by statement month · exact service dates kept alongside each bill.','muted'));heading.append(intro,button('+ Add statement',billForm,'primary'));panel.append(heading);
    const bills=[...data.bills].sort((a,b)=>b.statementDate.localeCompare(a.statementDate));
    if(!bills.length)panel.append(make('p','Add a statement to start your utility history.','empty-activity'));
    else {const chart=make('div',undefined,'bill-chart');chart.setAttribute('aria-label','New charges by statement month');const max=Math.max(1,...bills.map(b=>Math.abs(b.chargesCents)));for(const b of [...bills].reverse()){const col=make('div');col.append(make('strong',cash(b.chargesCents)));const bar=make('i');bar.style.height=Math.max(3,Math.abs(b.chargesCents)/max*72)+'px';col.append(bar,make('span',month(b.month)));chart.append(col);}panel.append(chart,make('p','New charges per statement. Missing statements are not treated as zero.','small muted'));
      const scroll=make('div',undefined,'table-wrap'),table=make('table',undefined,'bill-table'),head=make('thead'),tr=make('tr');['Statement','Service period','Due','New charges','Prior balance / credit','Payments reported','Statement total','PDFs'].forEach(s=>tr.append(make('th',s)));head.append(tr);table.append(head);const body=make('tbody');
      for(const b of bills){const r=make('tr');r.append(make('td',date(b.statementDate)),make('td',`${date(b.periodStart)} – ${date(b.periodEnd)}`),make('td',date(b.dueDate)),make('td',cash(b.chargesCents)),make('td',cash(b.previousCents)),make('td',cash(b.paymentsCents)),make('td',cash(b.totalCents)));const links=make('td');data.files.filter(f=>f.billId===b._id).forEach((f,i)=>links.append(button(i?'PDF '+(i+1):'View PDF',()=>preview(f),'file-link')));links.append(button('+ PDF',()=>upload({billId:b._id},'Attach statement PDF'),'quiet'));r.append(links);body.append(r);if(b.note){const n=make('tr'),td=make('td',b.note,'bill-note');td.colSpan=8;n.append(td);body.append(n);}}
      table.append(body);scroll.append(table);panel.append(scroll,make('p','Payments reported are historical amounts listed on each statement. They do not mark the current bill paid. Rent totals exclude utilities.','small muted'));}
    root.append(panel);
    const proof=make('section',undefined,'panel proof-library'),ph=make('div',undefined,'section-heading'),pi=make('div');pi.append(make('h2','Payment proof library'),make('p','Keep bank screenshots together and check each matched rent payment. Attachments do not add money to the ledger.','muted'));proof.id='rent-proof-library';ph.append(pi,button('+ Add screenshot',()=>upload({},'Add payment screenshot')));proof.append(ph);
    const files=data.files.filter(f=>!f.billId);if(!files.length)proof.append(make('p','Attach proof from Payment activity, or add a screenshot here.','muted'));
    for(const f of files){const details=make('details'),summary=make('summary',`${f.name} · ${f.paymentIds.length} linked payment${f.paymentIds.length===1?'':'s'}${f.entries?.some(e=>!e.paymentId)?' · review needed':''}`);details.append(summary,button('View full screenshot',()=>preview(f),'file-link'),button('Link to payment',()=>linkProof(f),'quiet'));
      if(f.entries){const list=make('div',undefined,'proof-entries');for(const e of f.entries){const p=e.paymentId?ledger.payments.find(p=>p._id===e.paymentId):null;const cfg=ledger.months.find(m=>m.month===e.month)?.config||ledger.months[0]?.config;const row=make('div');row.append(make('strong',`${cfg?.people[e.payer]?.name||'Resident'} · ${cash(e.amountCents)}`),make('span',`${date(e.date)} · ${e.status}${e.month?' · Rent '+month(e.month):''}`),make('p',e.memo||'No transfer memo shown.'),make('span',p&&!p.voidedAt?`${p.checked?'✓ Checked':'Linked · unchecked'} · ${e.review}`:'Review: '+(p?.voidedAt?'Linked receipt was voided.':e.review),'proof-state'));list.append(row);}details.append(list);}proof.append(details);}
    root.append(proof);
  }
  return {load(value,l){data=value||{bills:[],files:[]};ledger=l;render();},paymentControls,hasChanges:()=>pending||draft,clear(){generation++;pending=draft=false;data={bills:[],files:[]};ledger={months:[],payments:[]};dialog.close();dialog.replaceChildren();root.replaceChildren();revoke();}};
};
