/* Private payment evidence and statement-date utility log. */
window.RentRecords = function ({root,call,fileRequest,refresh,canEdit}) {
  const make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  const cash=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
  const date=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
  const month=d=>new Date(d+'-15T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'});
  const button=(label,fn,cls='outline')=>{const b=make('button',label,cls);b.type='button';b.onclick=fn;return b;};
  let data={bills:[],files:[]},ledger={months:[],payments:[]},generation=0,pending=false,draft=false,urls=[],viewSerial=0,currentView=null;
  const dialog=make('dialog',undefined,'record-dialog');dialog.setAttribute('aria-label','Rent documents');document.body.append(dialog);
  function revoke(){urls.forEach(u=>URL.revokeObjectURL(u));urls=[];}
  function close(){if(pending)return;viewSerial++;currentView=null;dialog.close();dialog.replaceChildren();draft=false;revoke();}
  dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
  function open(title){if(pending||draft||!canEdit()||bills.hasChanges())return false;viewSerial++;currentView=null;revoke();dialog.replaceChildren();const heading=make('div',undefined,'dialog-heading');heading.append(make('h2',title),button('Close',close,'quiet'));dialog.append(heading);dialog.showModal();return true;}
  async function preview(f,p){if(p&&!p.voidedAt){openPayments(p.month,p.payer);return;}if(!open(f.name))return;const g=generation,view=viewSerial,msg=make('p','Loading private file…');dialog.append(msg);try{const blob=await fileRequest('GET',{id:f._id});if(g!==generation||view!==viewSerial||!dialog.open)return;const url=URL.createObjectURL(blob);urls.push(url);msg.remove();const a=make('a','Download original');a.href=url;a.download=f.name;dialog.append(a);if(f.type==='application/pdf'){const frame=make('iframe');frame.title=f.name;frame.src=url;frame.className='document-preview';dialog.append(frame);}else{const img=make('img');img.alt=f.name;img.src=url;img.className='proof-preview';dialog.append(img);}}catch(e){if(g===generation)msg.textContent='Couldn’t load the file. Close and try again.';}}
  function upload(target,title,after){if(!open(title))return;
    const form=make('form'),label=make('label','Choose screenshot or PDF'),input=make('input'),local=make('div'),error=make('p','','form-error');input.type='file';input.accept='image/png,image/jpeg,image/webp,application/pdf';input.id='rent-upload';label.htmlFor=input.id;input.required=true;
    const submit=make('button','Save attachment','primary');submit.type='submit';let key=crypto.randomUUID(),selected=null;
    input.onchange=()=>{selected=input.files[0];key=crypto.randomUUID();draft=!!selected;revoke();local.replaceChildren();if(selected?.type.startsWith('image/')){const img=make('img');const url=URL.createObjectURL(selected);urls.push(url);img.src=url;img.alt='Attachment preview';img.className='proof-preview';local.append(img);}else if(selected)local.append(make('p',selected.name));};
    form.append(label,input,local,make('p','Attaching a file does not change payment totals or mark a receipt checked.','muted'),error,submit);dialog.append(form);
    form.onsubmit=async e=>{e.preventDefault();if(pending||!selected)return;const g=generation;pending=true;input.disabled=submit.disabled=true;error.textContent='Uploading…';try{await fileRequest('POST',target,selected,key);if(g!==generation)return;pending=false;draft=false;close();await refresh();if(g===generation)after?.();}catch(e){if(g===generation)error.textContent=e.message+' Your file is kept here for retry.';}finally{if(g===generation){pending=false;input.disabled=submit.disabled=false;}}};
  }
  function checkControl(p,labelText='Payment checked',compact=false){
    const label=make('label',undefined,compact?'cell-check':'check proof-check'),input=make('input');input.type='checkbox';input.checked=!!p.checked;input.setAttribute('aria-label',labelText);label.title=p.checked?`Checked by ${p.checkedBy||'a workspace member'}`:'Mark this receipt checked';label.append(input);if(!compact)label.append(make('span',p.checked?'✓ Checked':'Check payment'));
    input.onchange=async()=>{if(pending||draft||bills.hasChanges()||!canEdit()){input.checked=!!p.checked;return;}const g=generation;pending=true;input.disabled=true;try{await call('mutation','setConfirmation',{id:p._id,checked:input.checked});if(g!==generation)return;pending=false;await refresh();}catch{if(g===generation){input.checked=!!p.checked;const err=make('span','Couldn’t save check. Try again.','form-error');label.append(err);}}finally{if(g===generation){pending=false;input.disabled=false;}}};return label;
  }
  function paymentControls(p){const wrap=make('div',undefined,'payment-proof-actions');if(!p.voidedAt)wrap.append(checkControl(p),button('+ Attach proof',()=>upload({paymentId:p._id},'Attach payment proof'),'quiet'));data.files.filter(f=>f.paymentIds.includes(p._id)).forEach(f=>wrap.append(button('↗ '+f.name,()=>preview(f,p),'file-link')));return wrap;}
  function payerName(m,payer){return payer===3?'Affil':ledger.months.find(x=>x.month===m)?.config.people[payer]?.name||ledger.months[0]?.config.people[payer]?.name||'Resident';}
  function cellControls(m,payer){
    const wrap=make('div',undefined,'cell-receipts'),receipts=ledger.payments.filter(p=>p.month===m&&p.payer===payer&&!p.voidedAt);
    if(!receipts.length)return wrap;
    const attached=data.files.filter(f=>receipts.some(p=>f.paymentIds.includes(p._id))),checked=receipts.every(p=>p.checked),name=payerName(m,payer);
    const proof=button('',()=>openPayments(m,payer),'cell-proof'+(attached.length?' has-proof':'')+(checked?' is-checked':''));
    proof.setAttribute('aria-label',`${month(m)} ${name} payment proof`);
    proof.title=`${receipts.length} receipt${receipts.length===1?'':'s'} · ${attached.length} attachment${attached.length===1?'':'s'} · ${checked?'Checked':'Not fully checked'}`;
    const icon=document.createElementNS('http://www.w3.org/2000/svg','svg');icon.setAttribute('viewBox','0 0 20 20');icon.setAttribute('aria-hidden','true');
    const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','M4 3.5h12a.5.5 0 0 1 .5.5v12a.5.5 0 0 1-.5.5H4a.5.5 0 0 1-.5-.5V4a.5.5 0 0 1 .5-.5ZM4 13l4-4 3 3 2-2 3.5 4M12.5 6.5h.01');icon.append(path);proof.append(icon);if(checked){const check=make('span','✓','proof-checkmark');check.setAttribute('aria-hidden','true');proof.append(check);}wrap.append(proof);return wrap;
  }
  function proofImage(f,p,url){
    const wrap=make('div',undefined,'proof-audit'),history=(data.marks||[]).filter(m=>m.fileId===f._id&&m.paymentId===p._id).sort((a,b)=>b.version-a.version),saved=history[0];
    const entries=(f.entries||[]).filter(e=>e.paymentId===p._id),caption=make('div',undefined,'proof-reference');
    caption.append(make('strong',`${payerName(p.month,p.payer)} · ${month(p.month)} rent · ${cash(p.amountCents)}`));
    caption.append(make('span',entries.length?entries.map(e=>`Received ${date(e.date)} · ${e.status}${e.memo?' · “'+e.memo+'”':''}`).join(' / '):`Receipt date: ${p.date.length===7?month(p.date)+' (day unspecified)':date(p.date)}`));
    const stage=make('div',undefined,'proof-stage'),img=make('img'),flag=make('div',undefined,'proof-row-flag'),tag=make('span',`Referenced payment · ${month(p.month)}`);
    img.src=url;img.alt=f.name;img.className='proof-preview';img.draggable=false;flag.append(tag);stage.append(img,flag);
    const toolbar=make('div',undefined,'proof-flag-toolbar'),status=make('p','','proof-flag-status');status.setAttribute('role','status');
    const editor=make('div',undefined,'proof-flag-editor');editor.hidden=true;
    let editing=false,y=saved?.y??0.45,height=saved?.height??0.045,key=crypto.randomUUID();
    const position=make('input'),size=make('input');position.type=size.type='range';position.min='0';position.max='1000';position.step='1';size.min='10';size.max='500';size.step='1';
    position.setAttribute('aria-label','Flag row position');size.setAttribute('aria-label','Flag row height');
    const positionLabel=make('label','Row position'),sizeLabel=make('label','Highlight height');positionLabel.append(position);sizeLabel.append(size);
    function draw(){y=Math.min(1-height,Math.max(0,y));flag.hidden=!editing&&(!saved||saved.removed);flag.style.top=(y*100)+'%';flag.style.height=(height*100)+'%';position.value=String(Math.round(y*1000));size.value=String(Math.round(height*1000));stage.classList.toggle('is-marking',editing);}
    function edit(){if(pending||draft||!canEdit())return;editing=draft=true;editor.hidden=false;editButton.hidden=true;key=crypto.randomUUID();status.textContent='Tap the payment row, or adjust its position and height below. Save to keep the flag.';draw();}
    function cancel(){if(pending)return;editing=draft=false;y=saved?.y??0.45;height=saved?.height??0.045;editor.hidden=true;editButton.hidden=false;status.textContent='';draw();}
    const editButton=button(saved&&!saved.removed?'Adjust row flag':'Flag payment row',edit,'outline');
    const save=button('Save row flag',()=>persist(false),'primary'),remove=button('Remove row flag',()=>persist(true),'quiet'),cancelButton=button('Cancel flag edit',cancel,'quiet');remove.hidden=!saved||saved.removed;
    async function persist(removed){if(pending||!canEdit())return;const g=generation;pending=true;[save,remove,cancelButton,position,size].forEach(n=>n.disabled=true);status.textContent='Saving flag…';try{
      await call('mutation','setProofMark',{fileId:f._id,paymentId:p._id,y,height,removed,expectedVersion:saved?.version||0,requestKey:key});if(g!==generation)return;pending=draft=editing=false;await refresh();
    }catch(e){if(g===generation)status.textContent=/another device/.test(e.message)?'This flag changed on another device. Cancel and reopen the receipt to load it.':'Couldn’t save the flag. Your position is kept here; try again.';}
    finally{if(g===generation){pending=false;[save,remove,cancelButton,position,size].forEach(n=>n.disabled=false);}}}
    stage.onclick=e=>{if(!editing||pending)return;const box=stage.getBoundingClientRect();y=(e.clientY-box.top)/box.height-height/2;key=crypto.randomUUID();draw();};
    position.oninput=()=>{y=Number(position.value)/1000;key=crypto.randomUUID();draw();};size.oninput=()=>{height=Number(size.value)/1000;key=crypto.randomUUID();draw();};
    editor.append(positionLabel,sizeLabel,save,cancelButton,remove);toolbar.append(editButton);wrap.append(caption,toolbar,status,stage,editor);
    if(history.length){const log=make('details',undefined,'proof-flag-history');log.append(make('summary',`Flag history · ${history.length} revision${history.length===1?'':'s'}`));for(const event of history){log.append(make('p',`${event.removed?'Removed':'Flagged'} · ${new Date(event.createdAt).toLocaleString()} · ${event.createdBy} · row ${Math.round(event.y*1000)/10}%–${Math.round((event.y+event.height)*1000)/10}%`));}wrap.append(log);}
    wrap.append(make('p','Row flags are saved separately. Download original keeps the uploaded image unchanged.','small muted'));draw();return wrap;
  }
  async function inlineFile(f,container,view,p){const g=generation,status=make('p','Loading proof…','muted');container.append(status);try{const blob=await fileRequest('GET',{id:f._id});if(g!==generation||view!==viewSerial||!dialog.open)return;const url=URL.createObjectURL(blob);urls.push(url);status.remove();const link=make('a','Download '+f.name);link.href=url;link.download=f.name;container.append(link);if(p&&f.type.startsWith('image/')){container.append(proofImage(f,p,url));return;}const element=make(f.type==='application/pdf'?'iframe':'img');element.src=url;element.className=f.type==='application/pdf'?'document-preview':'proof-preview';if(f.type==='application/pdf')element.title=f.name;else element.alt=f.name;container.append(element);}catch{if(g===generation&&view===viewSerial)status.textContent='Couldn’t load proof. Close and reopen to retry.';}}
  function openPayments(m,payer){if(!open(`${payerName(m,payer)} · ${month(m)}`))return;currentView=()=>openPayments(m,payer);const view=viewSerial,receipts=ledger.payments.filter(p=>p.month===m&&p.payer===payer&&!p.voidedAt);
    dialog.append(make('p','Check each receipt and keep its screenshot alongside it.','muted'));
    for(const p of receipts){const section=make('section',undefined,'receipt-detail');section.append(make('h3',`${cash(p.amountCents)} · ${p.date}`),make('p',p.note||'','muted'),checkControl(p,`Receipt ${cash(p.amountCents)} checked`),button('+ Attach proof',()=>upload({paymentId:p._id},`Proof · ${payerName(m,payer)} · ${month(m)}`,()=>openPayments(m,payer)),'outline'),button('Use existing screenshot',()=>chooseExisting(p),'quiet'));
      for(const f of data.files.filter(f=>f.paymentIds.includes(p._id))){section.append(make('p','Attached: '+f.name,'small'));const container=make('div');section.append(container);void inlineFile(f,container,view,p);}dialog.append(section);}
  }
  function chooseExisting(p){if(!open('Choose payment proof'))return;const list=data.files.filter(f=>!f.billId&&!f.paymentIds.includes(p._id));if(!list.length)dialog.append(make('p','No other screenshots saved. Use Attach proof to upload one.'));for(const f of list){const b=button(f.name,async()=>{if(pending)return;const g=generation;pending=true;b.disabled=true;try{await call('mutation','linkFile',{id:f._id,paymentId:p._id});if(g!==generation)return;pending=false;close();await refresh();openPayments(p.month,p.payer);}catch{if(g===generation)b.textContent='Couldn’t link. Try again.';}finally{if(g===generation){pending=false;b.disabled=false;}}},'file-choice');dialog.append(b);}}
  function linkProof(f){if(!open('Link screenshot to a payment'))return;const form=make('form'),label=make('label','Payment'),select=make('select'),error=make('p','','form-error'),save=make('button','Link payment','primary');select.id='proof-payment';label.htmlFor=select.id;select.setAttribute('aria-label','Payment to link');save.type='submit';
    const candidates=ledger.payments.filter(p=>!p.voidedAt&&!f.paymentIds.includes(p._id)).sort((a,b)=>b.month.localeCompare(a.month));
    for(const p of candidates){const name=ledger.months.find(m=>m.month===p.month)?.config.people[p.payer]?.name||(p.payer===3?'Affil':'Resident');const o=make('option',`${month(p.month)} · ${name} · ${cash(p.amountCents)} · ${p.date}`);o.value=p._id;select.append(o);}
    form.append(label,select,make('p','You can link the same screenshot to several receipts. Check each payment separately after reviewing the proof.','muted'),error,save);dialog.append(form);SearchableSelect.enhance(select);save.disabled=!candidates.length;
    form.onsubmit=async e=>{e.preventDefault();if(pending)return;const g=generation;pending=true;save.disabled=true;try{await call('mutation','linkFile',{id:f._id,paymentId:select.value});if(g!==generation)return;pending=false;close();await refresh();}catch(e){if(g===generation)error.textContent='Couldn’t link the file. Try again.';}finally{if(g===generation){pending=false;save.disabled=false;}}};
  }
  function openBill(b){if(!b||!open('PG&E · '+month(b.month)))return;currentView=()=>openBill(data.bills.find(x=>x._id===b._id)||b);const view=viewSerial;dialog.append(make('p',`Statement ${date(b.statementDate)} · Service ${date(b.periodStart)} – ${date(b.periodEnd)} · Due ${date(b.dueDate)}`,'muted'),make('p',b.note||''),button('+ Attach PDF',()=>upload({billId:b._id},'Attach statement PDF',()=>openBill(b))));for(const f of data.files.filter(f=>f.billId===b._id)){const container=make('div');dialog.append(container);void inlineFile(f,container,view);}}
  function unmatched(){return data.files.filter(f=>!f.billId).flatMap(f=>(f.entries||[]).filter(e=>!e.paymentId||!ledger.payments.some(p=>p._id===e.paymentId&&!p.voidedAt)).map(e=>({f,e})));}
  function openUnmatched(){if(!open('Unmatched transfers'))return;dialog.append(make('p','These screenshot entries need a month or amount reviewed before they can be linked to a rent receipt.','muted'));for(const {f,e} of unmatched()){const row=make('section',undefined,'receipt-detail');row.append(make('strong',`${payerName(e.month,e.payer)} · ${cash(e.amountCents)} · ${date(e.date)}`),make('p',e.memo||'No memo shown.'),make('p',e.review),button('View screenshot',()=>preview(f),'file-link'),button('Link screenshot to receipt',()=>linkProof(f),'quiet'));dialog.append(row);}}
  const bills=RentBillSheet({root,save:args=>call('mutation','saveBillGrid',args),refresh,canEdit:()=>!pending&&!draft&&canEdit(),openFiles:openBill});
  return {load(value,l){data=value||{bills:[],files:[]};ledger=l;bills.load(data);if(currentView&&dialog.open&&!pending&&!draft){const view=currentView;view();}},paymentControls,cellControls,openPayments,openUnmatched,unmatchedCount:()=>unmatched().length,hasChanges:()=>pending||draft||bills.hasChanges(),setLocked:value=>bills.setLocked(value),clear(){generation++;viewSerial++;currentView=null;pending=draft=false;data={bills:[],files:[]};ledger={months:[],payments:[]};dialog.close();dialog.replaceChildren();bills.clear();revoke();}};
};
