const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const {chromium,webkit}=require('playwright');const engine=process.env.QUESTIONS_BROWSER==='webkit'?webkit:chromium;
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAK0lEQVR4nGN48u4OTRHDqAWjFoxaMGrBqAWjFoxaMGrBqAWjFoxaMFQsAAB7EbiXgjbI0AAAAABJRU5ErkJggg==','base64');
function store(){return {items:[],events:[],files:[],failUpload:false,failSave:false};}
async function open(browser,width=1280,db=store(),mode='signed-in'){
 const page=await browser.newPage({viewport:{width,height:900},hasTouch:width<800,isMobile:width<800});page.setDefaultTimeout(6000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(mode=>{const token='test.'+btoa(JSON.stringify({aud:'convex'}))+'.test';const session={id:'test',getToken:async()=>token};window.__internal_ClerkUICtor={};window.Clerk={session:mode==='signed-out'?null:session,load:async()=>{},mountSignIn:n=>n.textContent='Sign in form',unmountSignIn:n=>n.textContent='',addListener(fn){window.changeSession=s=>{this.session=s;fn({session:s});};},signOut:async()=>window.changeSession(null)};},mode);
 await page.route('**/*',async route=>{
  const url=new URL(route.request().url());if(url.protocol==='blob:')return route.continue();if(url.hostname==='localhost'){let filename=url.pathname.endsWith('/')?'tools/payment/questions/index.html':url.pathname.replace(/^\//,'');let body=await fs.readFile(path.join(__dirname,'../../../..',filename));if(filename.endsWith('index.html'))body=Buffer.from(body.toString().replace(/<script\b[^>]*src="https:[\s\S]*?<\/script>/g,''));return route.fulfill({body,contentType:filename.endsWith('.js')?'text/javascript':filename.endsWith('.css')?'text/css':'text/html'});}
  if(url.hostname.endsWith('.convex.site')){if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS'}});if(route.request().method()==='POST'){if(db.failUpload)return route.fulfill({status:500,body:'Failed',headers:{'Access-Control-Allow-Origin':'*'}});const key=route.request().headers()['x-request-key'];if(!db.files.some(f=>f.requestKey===key))db.files.push({_id:'file'+db.files.length,ticketId:url.searchParams.get('id'),name:'charge.png',requestKey:key});return route.fulfill({json:{},headers:{'Access-Control-Allow-Origin':'*'}});}return route.fulfill({body:png,contentType:'image/png',headers:{'Access-Control-Allow-Origin':'*'}});}
  if(!url.hostname.endsWith('.convex.cloud'))return route.abort();const {path:endpoint,args}=route.request().postDataJSON();const name=endpoint.split(':')[1];if(mode==='denied')return route.fulfill({json:{status:'error',errorMessage:'This account is not authorized for payment questions.'}});
  let value=null;const t=db.items.find(x=>x._id===args.id);if(name==='verify')value={email:'owner@example.com'};if(name==='list')value=db.items;
  if(name==='saveNote'){
   if(db.delaySave)await db.delaySave();if(db.failSave)return route.abort();
   const plain=nodes=>nodes.map(n=>n.type==='text'?n.text:n.type==='br'?'\n':plain(n.children||[])+(['p','li'].includes(n.type)?'\n':'')).join('');
   const body=plain(args.richText).trim();let item=args.id?db.items.find(t=>t._id===args.id):db.items.find(t=>t.requestKey===args.requestKey);
   if(args.id&&item.version!==args.expectedVersion)return route.fulfill({json:{status:'error',errorMessage:'This question changed on another device. Refresh before saving.'}});
   if(!item){item={_id:'question'+db.items.length,status:'open',version:0,createdAt:Date.now(),createdBy:'owner@example.com',requestKey:args.requestKey};db.items.push(item);}
   Object.assign(item,{title:args.title||body.split('\n')[0].slice(0,100)||'Untitled note',context:body,richText:args.richText,updatedAt:Date.now(),version:item.version+1});value={id:item._id,version:item.version};
  }
  if(name==='move'){if(t.version!==args.expectedVersion)return route.fulfill({json:{status:'error',errorMessage:'This question changed on another device. Refresh before saving.'}});t.status=args.status;t.version++;t.updatedAt=Date.now();db.events.push({ticketId:t._id,kind:args.status,text:'',createdAt:Date.now()});value={version:t.version};}
  if(name==='create'){if(db.failSave)return route.abort();let item=db.items.find(t=>t.requestKey===args.requestKey);if(!item){item={...args,_id:'question'+db.items.length,status:'open',receivedCents:0,version:1,createdAt:Date.now(),updatedAt:Date.now(),createdBy:'owner@example.com'};db.items.push(item);}value=item._id;}
  if(name==='detail'){if(db.delayDetail)await db.delayDetail();value={item:t,events:db.events.filter(e=>e.ticketId===args.id),files:db.files.filter(f=>f.ticketId===args.id)};}
  if(name==='edit'||name==='update'){if(db.failSave)return route.abort();if(t.version!==args.expectedVersion)return route.fulfill({json:{status:'error',errorMessage:'This question changed on another device. Refresh before saving.'}});if(name==='edit')Object.assign(t,args);else{t.status=args.status||t.status;t.receivedCents+=args.amountCents||0;db.events.push({...args,ticketId:t._id,kind:args.amountCents?'payment':args.status||'note',author:'owner@example.com',createdAt:Date.now()});}t.version++;t.updatedAt=Date.now();}
  return route.fulfill({json:{status:'success',value}});
 });
 await page.goto('http://localhost/tools/payment/questions/');if(mode==='signed-in')await page.locator('#app').waitFor();return {page,db,errors};
}
async function writeNote(page,text='Ask Mom about the Chase trip.'){await page.locator('#new').click();await page.getByRole('textbox',{name:'Note',exact:true}).fill(text);await page.locator('#save').click();await page.locator('#save-state').filter({hasText:/^Saved$/}).waitFor();}
test('rich note autosaves, reopens with formatting, and moves through the queue without a form',async()=>{const browser=await engine.launch();try{for(const width of [390,1280]){const {page,db,errors}=await open(browser,width);await writeNote(page);const editor=page.getByRole('textbox',{name:'Note',exact:true});await editor.press('ControlOrMeta+A');await page.getByRole('button',{name:/^Bold/}).click();await page.locator('#save').click();await page.locator('#save-state').filter({hasText:/^Saved$/}).waitFor();assert.match(JSON.stringify(db.items[0].richText),/strong/);assert.equal(db.items[0].amountCents,undefined);await page.locator('[data-move="waiting"]').click();await page.locator('#note-stage').filter({hasText:'Waiting'}).waitFor();assert.equal(db.items[0].status,'waiting');await page.locator('[data-move="resolved"]').click();await page.locator('#note-stage').filter({hasText:'Done'}).waitFor();assert.equal(db.items[0].status,'resolved');assert.equal(await page.locator('dialog[open]').count(),0);await page.locator('#files').setInputFiles({name:'charge.png',mimeType:'image/png',buffer:png});await page.locator('.screenshot img').waitFor();assert.ok(await page.locator('.screenshot img').evaluate(n=>n.complete&&n.naturalWidth>0));await page.locator('[data-move="open"]').click();await page.locator('#note-stage').filter({hasText:'Inbox'}).waitFor();await page.screenshot({path:path.join(os.tmpdir(),`payment-notes-${engine.name()}-${width}.png`),fullPage:true});const size=await page.evaluate(()=>[document.documentElement.scrollWidth,innerWidth]);assert.ok(size[0]<=size[1]);await page.locator('#new').click();if(width<800)await page.locator('#back').click();await page.locator('.ticket').first().click();await page.locator('.rich-note-input strong').waitFor();assert.equal(await page.locator('.rich-note-input strong').textContent(),'Ask Mom about the Chase trip.');assert.deepEqual(errors,[]);await page.close();}}finally{await browser.close();}});
test('typing during a slow save keeps the latest text; failed saves retain and retry the draft',async()=>{const browser=await engine.launch();try{const {page,db,errors}=await open(browser);await page.locator('#new').click();const editor=page.getByRole('textbox',{name:'Note',exact:true});let release;db.delaySave=()=>new Promise(r=>release=r);await editor.fill('First draft');await page.locator('#save').click();await page.waitForTimeout(100);await editor.fill('First draft, with more context while saving.');db.delaySave=null;release();await page.locator('#save-state').filter({hasText:/^Saved$/}).waitFor();assert.equal(db.items.length,1);assert.equal(db.items[0].context,'First draft, with more context while saving.');db.failSave=true;await editor.fill('Keep this during an outage');await page.locator('#save').click();await page.locator('#save-state.error').waitFor();assert.equal(await editor.textContent(),'Keep this during an outage');db.failSave=false;await page.locator('#save').click();await page.locator('#save-state').filter({hasText:/^Saved$/}).waitFor();assert.equal(db.items[0].context,'Keep this during an outage');assert.deepEqual(errors,[]);}finally{await browser.close();}});
test('screenshot-only notes and failed uploads retry without duplicating notes',async()=>{const browser=await engine.launch();try{const {page,db,errors}=await open(browser,320);await page.locator('#new').click();db.failUpload=true;await page.locator('#files').setInputFiles({name:'charge.png',mimeType:'image/png',buffer:png});await page.getByRole('button',{name:/Retry screenshot/}).waitFor();assert.equal(db.items.length,1);assert.equal(db.items[0].title,'Untitled note');db.failUpload=false;await page.getByRole('button',{name:/Retry screenshot/}).click();await page.locator('.screenshot img').waitFor();assert.equal(db.files.length,1);assert.equal(db.items.length,1);assert.deepEqual(errors,[]);}finally{await browser.close();}});
test('paste keeps safe formatting and strips executable HTML; sign-out clears even a pending save',async()=>{const browser=await engine.launch();try{const {page,db,errors}=await open(browser);await page.locator('#new').click();await page.locator('.rich-note-input').evaluate(el=>{const clipboardData=new DataTransfer();clipboardData.setData('text/html','<p><b>Keep this</b><img src=x onerror="window.bad=true"><a href="javascript:alert(1)">link text</a><script>window.bad=true</script></p>');el.dispatchEvent(new ClipboardEvent('paste',{clipboardData,bubbles:true,cancelable:true}));});await page.locator('#save').click();await page.locator('#save-state').filter({hasText:/^Saved$/}).waitFor();assert.equal(await page.evaluate(()=>window.bad),undefined);assert.doesNotMatch(JSON.stringify(db.items[0].richText),/javascript:|script|onerror/);let release;db.delaySave=()=>new Promise(r=>release=r);await page.locator('.rich-note-input').fill('Pending secret note');await page.locator('#save').click();await page.waitForTimeout(100);await page.locator('#sign-out').click();release();await page.getByText('Sign in form',{exact:true}).waitFor();await page.waitForTimeout(100);assert.equal(await page.locator('#app').isVisible(),false);assert.equal(await page.locator('#note-title').inputValue(),'');assert.equal(await page.locator('.rich-note-input').count(),0);assert.deepEqual(errors,[]);}finally{await browser.close();}});
test('unapproved and signed-out sessions never show the editor',async()=>{const browser=await engine.launch();try{for(const mode of ['denied','signed-out']){const {page}=await open(browser,390,store(),mode);await page.getByText(mode==='signed-out'?'Sign in form':'This account doesn’t have access. Use your approved email.',{exact:true}).waitFor();assert.equal(await page.locator('#app').isVisible(),false);await page.close();}}finally{await browser.close();}});
test('notes save automatically and a queue move flushes the latest unsaved text',async()=>{const browser=await engine.launch();try{const {page,db,errors}=await open(browser);await page.locator('#new').click();await page.locator('.rich-note-input').fill('This should save by itself.');await page.locator('#save-state').filter({hasText:/^Saved$/}).waitFor();assert.equal(db.items[0].context,'This should save by itself.');await page.locator('.rich-note-input').fill('Updated right before moving.');await page.locator('[data-move="waiting"]').click();await page.locator('#note-stage').filter({hasText:'Waiting'}).waitFor();assert.equal(db.items[0].context,'Updated right before moving.');assert.equal(db.items[0].status,'waiting');assert.deepEqual(errors,[]);}finally{await browser.close();}});
