const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const {chromium,webkit}=require('playwright');const engine=process.env.QUESTIONS_BROWSER==='webkit'?webkit:chromium;
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAK0lEQVR4nGN48u4OTRHDqAWjFoxaMGrBqAWjFoxaMGrBqAWjFoxaMFQsAAB7EbiXgjbI0AAAAABJRU5ErkJggg==','base64');
function store(){return {items:[],events:[],files:[],failUpload:false,failSave:false};}
async function open(browser,width=1280,db=store(),mode='signed-in'){
 const page=await browser.newPage({viewport:{width,height:900},hasTouch:width<800,isMobile:width<800});page.setDefaultTimeout(6000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(mode=>{const token='test.'+btoa(JSON.stringify({aud:'convex'}))+'.test';const session={id:'test',getToken:async()=>token};window.__internal_ClerkUICtor={};window.Clerk={session:mode==='signed-out'?null:session,load:async()=>{},mountSignIn:n=>n.textContent='Sign in form',unmountSignIn:n=>n.textContent='',addListener(fn){window.changeSession=s=>{this.session=s;fn({session:s});};},signOut:async()=>window.changeSession(null)};},mode);
 await page.route('**/*',async route=>{
  const url=new URL(route.request().url());if(url.protocol==='blob:')return route.continue();if(url.hostname==='localhost'){let filename=url.pathname.endsWith('/')?'tools/payment/questions/index.html':url.pathname.replace(/^\//,'');let body=await fs.readFile(path.join(__dirname,'../../../..',filename));if(filename.endsWith('index.html'))body=Buffer.from(body.toString().replace(/<script\b[^>]*src="https:[\s\S]*?<\/script>/g,''));return route.fulfill({body,contentType:filename.endsWith('.js')?'text/javascript':filename.endsWith('.css')?'text/css':'text/html'});}
  if(url.hostname.endsWith('.convex.site')){if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS'}});if(route.request().method()==='POST'){if(db.failUpload)return route.fulfill({status:500,body:'Failed',headers:{'Access-Control-Allow-Origin':'*'}});const key=route.request().headers()['x-request-key'];if(!db.files.some(f=>f.requestKey===key))db.files.push({_id:'file'+db.files.length,ticketId:url.searchParams.get('id'),name:'charge.png',requestKey:key});return route.fulfill({json:{},headers:{'Access-Control-Allow-Origin':'*'}});}return route.fulfill({body:png,contentType:'image/png',headers:{'Access-Control-Allow-Origin':'*'}});}
  if(!url.hostname.endsWith('.convex.cloud'))return route.abort();const {path:endpoint,args}=route.request().postDataJSON();const name=endpoint.split(':')[1];if(mode==='denied')return route.fulfill({json:{status:'error',errorMessage:'This account is not authorized for payment questions.'}});
  let value=null;const t=db.items.find(x=>x._id===args.id);if(name==='verify')value={email:'owner@example.com'};if(name==='list')value=db.items;
  if(name==='create'){if(db.failSave)return route.abort();let item=db.items.find(t=>t.requestKey===args.requestKey);if(!item){item={...args,_id:'question'+db.items.length,status:'open',receivedCents:0,version:1,createdAt:Date.now(),updatedAt:Date.now(),createdBy:'owner@example.com'};db.items.push(item);}value=item._id;}
  if(name==='detail'){if(db.delayDetail)await db.delayDetail();value={item:t,events:db.events.filter(e=>e.ticketId===args.id),files:db.files.filter(f=>f.ticketId===args.id)};}
  if(name==='edit'||name==='update'){if(db.failSave)return route.abort();if(t.version!==args.expectedVersion)return route.fulfill({json:{status:'error',errorMessage:'This question changed on another device. Refresh before saving.'}});if(name==='edit')Object.assign(t,args);else{t.status=args.status||t.status;t.receivedCents+=args.amountCents||0;db.events.push({...args,ticketId:t._id,kind:args.amountCents?'payment':args.status||'note',author:'owner@example.com',createdAt:Date.now()});}t.version++;t.updatedAt=Date.now();}
  return route.fulfill({json:{status:'success',value}});
 });
 await page.goto('http://localhost/tools/payment/questions/');if(mode==='signed-in')await page.locator('#app').waitFor();return {page,db,errors};
}
async function create(page){await page.locator('#new').click();await page.locator('#title').fill('Chase Travel — who owes Mom?');await page.locator('#amount').fill('2337.06');await page.locator('#transactionDate').fill('2026-07-22');await page.locator('#cardholder').fill('Mom');await page.locator('#card').fill('Chase · 9809');await page.locator('#payer').fill('Alex');await page.locator('#payee').fill('Mom');await page.locator('#expected').fill('100');await page.locator('#context').fill('Ask which trip this was.');await page.locator('#files').setInputFiles({name:'charge.png',mimeType:'image/png',buffer:png});await page.locator('#ticket-submit').click();await page.locator('#ticket-dialog').waitFor({state:'hidden'});await page.locator('.screenshot img').waitFor();assert.ok(await page.locator('.screenshot img').evaluate(n=>n.complete&&n.naturalWidth>0));}
test('capture, partial repayment, resolution, reopen and search work on desktop and phone',async()=>{const browser=await engine.launch();try{for(const width of [390,1280]){const {page,db,errors}=await open(browser,width);await create(page);assert.equal(db.items.length,1);assert.equal(db.files.length,1);assert.equal(await page.locator('#open-count').textContent(),'1');await page.getByRole('button',{name:'Log repayment',exact:true}).click();await page.locator('#repayment').fill('40');await page.locator('#update-text').fill('Alex sent Mom $40 by Zelle today.');await page.getByRole('button',{name:'Save update',exact:true}).click();await page.locator('#update-dialog').waitFor({state:'hidden'});await page.getByText('Repayment received · $40.00',{exact:true}).waitFor();assert.equal(db.items[0].receivedCents,4000);assert.equal(db.items[0].status,'open');assert.equal(await page.locator('#owed-total').textContent(),'$60.00');await page.getByRole('button',{name:'Resolve',exact:true}).click();await page.locator('#update-text').fill('Remaining $60 was my share; all sorted.');await page.getByRole('button',{name:'Save update',exact:true}).click();await page.locator('#update-dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'Reopen',exact:true}).waitFor();assert.equal(db.items[0].receivedCents,4000);assert.equal(await page.locator('#open-count').textContent(),'0');await page.getByRole('button',{name:'Reopen',exact:true}).click();await page.locator('#update-text').fill('Need to verify the transfer.');await page.getByRole('button',{name:'Save update',exact:true}).click();await page.locator('#update-dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'Resolve',exact:true}).waitFor();const size=await page.evaluate(()=>[document.documentElement.scrollWidth,innerWidth]);assert.ok(size[0]<=size[1]);await page.screenshot({path:path.join(os.tmpdir(),`payment-questions-${engine.name()}-${width}.png`),fullPage:true});if(width<800)await page.getByRole('button',{name:'← All questions',exact:true}).click();await page.locator('#search').fill('zzzz');assert.equal(await page.locator('.ticket').count(),0);await page.locator('#search').fill('Alex');assert.equal(await page.locator('.ticket').count(),1);assert.deepEqual(errors,[]);await page.close();}}finally{await browser.close();}});
test('failed uploads retry without duplicate tickets and save failures retain drafts',async()=>{const browser=await engine.launch();try{const {page,db,errors}=await open(browser,320);db.failUpload=true;await page.locator('#new').click();await page.locator('#files').setInputFiles({name:'charge.png',mimeType:'image/png',buffer:png});await page.locator('#ticket-submit').click();await page.getByRole('button',{name:'Retry screenshots'}).waitFor();assert.equal(db.items.length,1);db.failUpload=false;await page.getByRole('button',{name:'Retry screenshots'}).click();await page.locator('.screenshot img').waitFor();assert.equal(db.items.length,1);assert.equal(db.files.length,1);await page.getByRole('button',{name:'Add update',exact:true}).click();await page.locator('#update-text').fill('Keep this draft');db.failSave=true;await page.getByRole('button',{name:'Save update',exact:true}).click();await page.locator('#update-error').filter({hasText:'Couldn’t confirm'}).waitFor();assert.equal(await page.locator('#update-text').inputValue(),'Keep this draft');assert.equal(await page.locator('#update-dialog').isVisible(),true);assert.deepEqual(errors,[]);}finally{await browser.close();}});
test('signed-out and denied users see no ticket data; late detail cannot survive sign-out',async()=>{const browser=await engine.launch();try{for(const mode of ['signed-out','denied']){const {page}=await open(browser,390,store(),mode);await page.getByText(mode==='signed-out'?'Sign in form':'This account doesn’t have access to Payment questions. Use your approved email.',{exact:true}).waitFor();assert.equal(await page.locator('#app').isVisible(),false);await page.close();}const {page,db,errors}=await open(browser);await create(page);let release;db.delayDetail=()=>new Promise(r=>release=r);await page.locator('.ticket').click();await page.waitForTimeout(100);await page.locator('#sign-out').click();release();await page.getByText('Sign in form',{exact:true}).waitFor();await page.waitForTimeout(100);assert.equal(await page.locator('#detail').textContent(),'');assert.equal(await page.locator('#title').inputValue(),'');assert.deepEqual(errors,[]);}finally{await browser.close();}});
