const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {chromium,webkit}=require('playwright');const engine=process.env.RENT_BROWSER==='webkit'?webkit:chromium;
const config={rentCents:600000,loftCents:30000,bathroomCents:10000,people:[{name:'Alex',room:100,closet:20,creditCents:10000},{name:'Blair',room:130,closet:30,creditCents:100000},{name:'Casey',room:100,closet:20,creditCents:100000}]};
async function open(browser,width=1280,mode='signed-in'){
 const page=await browser.newPage({viewport:{width,height:960},hasTouch:width<800,isMobile:width<800});page.setDefaultTimeout(7000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const month=await page.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;});
 const db={months:[{_id:'month1',month,config:structuredClone(config),parkingCents:0,note:'',requestsSent:false,version:1,sourceNote:'Original spreadsheet history retained for review.',sourcePayments:[{payer:0,amountCents:190000,note:'Payment request, date unconfirmed.'}]}],payments:[],files:[],bills:[],marks:[],fail:false};
 if(mode==="empty")db.months=[];
 await page.addInitScript(mode=>{const session={id:'one',getToken:async()=>`test.${btoa(JSON.stringify({aud:'convex'}))}.test`};window.__internal_ClerkUICtor={};window.Clerk={session:mode==='signed-out'?null:session,load:async()=>{},mountSignIn:n=>n.textContent='Sign in form',unmountSignIn:n=>n.textContent='',addListener(fn){window.changeSession=s=>{this.session=s;fn({session:s});};},signOut:async()=>window.changeSession(null)};},mode);
 await page.route('**/*',async route=>{
  const url=new URL(route.request().url());if(url.protocol==='blob:')return route.continue();
  if(url.hostname==='localhost'){let filename=url.pathname.endsWith('/')?url.pathname+'index.html':url.pathname;let body=await fs.readFile(path.join(__dirname,'../../..',filename));if(filename.endsWith('.html'))body=Buffer.from(body.toString().replace(/<script\b[^>]*src="https:[\s\S]*?<\/script>/g,''));return route.fulfill({body,contentType:filename.endsWith('.js')?'text/javascript':filename.endsWith('.css')?'text/css':'text/html'});}
  if(url.hostname.endsWith('.convex.site')){
    if(route.request().method()==='GET')return route.fulfill({body:db.proofBytes||Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a0t0AAAAASUVORK5CYII=','base64'),contentType:'image/png'});
    if(db.failUpload)return route.abort();
    const key=route.request().headers()['x-request-key'];let f=db.files.find(f=>f.requestKey===key);if(!f){f={_id:'file'+db.files.length,name:decodeURIComponent(route.request().headers()['x-file-name']),type:route.request().headers()['content-type'],paymentIds:url.searchParams.get('paymentId')?[url.searchParams.get('paymentId')]:[],billId:url.searchParams.get('billId')||undefined,requestKey:key};db.files.push(f);}return route.fulfill({json:{id:f._id}});
  }
  if(!url.hostname.endsWith('.convex.cloud'))return route.abort();const {path:routePath,args}=route.request().postDataJSON();const name=routePath.split(':')[1];let value=null;
  if(mode==='denied')return route.fulfill({json:{status:'error',errorMessage:'This account is not authorized for Rent.'}});
  if(name==='verify')value={email:'test@example.com'};
  if(name==='overview')value={bills:db.bills,files:db.files,marks:db.marks};
  if(name==='setProofMark'){if(db.failMark)return route.abort();let mark=db.marks.find(m=>m.requestKey===args.requestKey);if(!mark){mark={...args,_id:'mark'+db.marks.length,version:args.expectedVersion+1,createdAt:Date.now(),createdBy:'test@example.com'};db.marks.push(mark);}value=mark._id;}
  if(name==='linkFile'){const f=db.files.find(f=>f._id===args.id);if(!f.paymentIds.includes(args.paymentId))f.paymentIds.push(args.paymentId);}
  if(name==='setConfirmation'){db.payments.find(p=>p._id===args.id).checked=args.checked;}
  if(name==='saveBillGrid'){
    if(db.failBills)return route.abort();
    for(const r of args.rows){let b=r.id?db.bills.find(b=>b._id===r.id):db.bills.find(b=>b.statementDate===r.statementDate);if(b?.lastEditKey===args.requestKey)continue;if(b&&(b.version||0)!==r.expectedVersion)return route.fulfill({json:{status:'error',errorMessage:'This statement changed on another device.'}});if(!b){b={_id:'bill'+db.bills.length};db.bills.push(b);}Object.assign(b,r,{version:r.expectedVersion+1,lastEditKey:args.requestKey});}value={saved:args.rows.length};
  }
  if(name==='saveBill'){let b=db.bills.find(b=>b.requestKey===args.requestKey);if(!b){b={...args,_id:'bill'+db.bills.length,month:args.statementDate.slice(0,7)};db.bills.push(b);}value=b._id;}
  if(name==='ledger')value={months:db.months,payments:db.payments};
  if(name==='saveGrid'){
   if(db.fail)return route.abort();
   for(const row of args.rows){let item=db.months.find(m=>m.month===row.month);if(item?.requestKey===args.requestKey)continue;if((item?.version||0)!==row.expectedVersion)return route.fulfill({json:{status:'error',errorMessage:'This month changed on another device.'}});if(!item){item={_id:'month'+db.months.length,month:row.month,note:'',requestsSent:false};db.months.push(item);}Object.assign(item,{config:row.config,parkingCents:row.parkingCents,version:row.expectedVersion+1,requestKey:args.requestKey});for(const receipt of row.receipts){db.payments.filter(p=>p.month===row.month&&p.payer===receipt.payer&&!p.voidedAt).forEach(p=>p.voidedAt=Date.now());if(receipt.amountCents)db.payments.push({...receipt,month:row.month,date:row.month,_id:'grid'+db.payments.length,createdAt:Date.now(),createdBy:'test@example.com',note:'Monthly total'});}}value={saved:args.rows.length};
  }
  if(name==='dashboard'){if(db.delayRead)await db.delayRead();const item=db.months.find(m=>m.month===args.month)||null;value={item,template:db.months[0]?.config||null,months:db.months.map(m=>({month:m.month})),payments:db.payments.filter(p=>p.month===args.month)};}
  if(name==='recordPayment'){if(db.delaySave)await db.delaySave();if(db.fail)return route.abort();let payment=db.payments.find(p=>p.requestKey===args.requestKey);if(!payment){payment={...args,_id:'payment'+db.payments.length,createdAt:Date.now(),createdBy:'test@example.com'};db.payments.push(payment);}value=payment._id;}
  if(name==='saveMonth'){if(db.fail)return route.abort();let item=db.months.find(m=>m.month===args.month);if(item&&item.version!==args.expectedVersion)return route.fulfill({json:{status:'error',errorMessage:'This month changed on another device. Refresh before saving.'}});if(!item){item={_id:'month'+db.months.length};db.months.push(item);}Object.assign(item,args,{version:args.expectedVersion+1});value=item._id;}
  if(name==='voidPayment'){db.payments.find(p=>p._id===args.id).voidedAt=Date.now();}
  return route.fulfill({json:{status:'success',value}});
 });
 await page.goto('http://localhost/tools/rent/');if(mode==='signed-in')await page.locator('#dashboard').waitFor();if(mode==='empty')await page.locator('#empty').waitFor();return {page,db,errors};
}
test('desktop and phone layouts, searchable payer picker, payment and void workflow',async()=>{
 const browser=await engine.launch();try{for(const width of [390,1280]){const {page,db,errors}=await open(browser,width);
  assert.equal(await page.locator('#remaining').textContent(),'$6,000.00');assert.equal(db.payments.length,0);
  await page.screenshot({path:path.join(os.tmpdir(),`rent-${engine.name()}-${width}.png`),fullPage:true});
  await page.locator('#record').click();await page.locator('#payment-dialog .search-select-trigger').click();const search=page.locator('#payment-dialog [role=combobox]');await search.fill('Blair');await page.getByRole('option',{name:'Blair',exact:true}).click();
  assert.equal(await page.locator('#amount').inputValue(),'1150.00');await page.locator('#amount').fill('500.00');await page.locator('#payment-submit').click();await page.locator('#payment-dialog').waitFor({state:'hidden'});await page.getByText('Partial',{exact:true}).waitFor();assert.equal(db.payments.length,1);
  await page.locator('#payments').getByRole('button',{name:'Void',exact:true}).click();await page.locator('#void-submit').click();await page.locator('#void-dialog').waitFor({state:'hidden'});assert.ok(db.payments[0].voidedAt);
  assert.equal(await page.locator('#remaining').textContent(),'$6,000.00');const size=await page.evaluate(()=>[document.documentElement.scrollWidth,innerWidth]);assert.ok(size[0]<=size[1],JSON.stringify(size));assert.deepEqual(errors,[]);await page.close();
 }}finally{await browser.close();}
});
test('new months inherit calculation only; editing, monthly notes and history persist',async()=>{
 const browser=await engine.launch();try{const {page,db,errors}=await open(browser);
  await page.locator('#note').fill('Waiting for transfer');await page.locator('#next').click();await page.locator('#notice').filter({hasText:/Save your monthly note/}).waitFor();await page.locator('#save-note').click();await page.locator('#sync').filter({hasText:/Up to date/}).waitFor();assert.equal(db.months[0].note,'Waiting for transfer');
  await page.locator('#next').click();await page.locator('#create').click();assert.equal(await page.locator('#parking-input').inputValue(),'0.00');await page.locator('#parking-input').fill('100');await page.locator('#config-submit').click();await page.locator('#config-dialog').waitFor({state:'hidden'});assert.equal(db.months.length,2);assert.equal(db.months[1].parkingCents,10000);assert.equal(db.months[1].note,'');assert.equal(db.months[0].parkingCents,0);assert.equal(await page.locator('#remaining').textContent(),'$5,900.00');assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
test('failed saves retain draft and retry once; sign-out clears data during a delayed request',async()=>{
 const browser=await engine.launch();try{const {page,db,errors}=await open(browser);await page.locator('#record').click();await page.locator('#amount').fill('99.99');db.fail=true;await page.locator('#payment-submit').click();await page.locator('#payment-error').filter({hasText:/Couldn’t save/}).waitFor();assert.equal(await page.locator('#amount').inputValue(),'99.99');db.fail=false;await page.locator('#payment-submit').click();await page.locator('#payment-dialog').waitFor({state:'hidden'});assert.equal(db.payments.length,1);
  let release;db.delayRead=()=>new Promise(r=>release=r);await page.locator('#refresh').click();await page.waitForTimeout(80);await page.locator('#sign-out').click();release();await page.getByText('Sign in form',{exact:true}).waitFor();await page.waitForTimeout(80);assert.equal(await page.locator('#app').isVisible(),false);assert.equal(await page.locator('#people').textContent(),'');assert.equal(await page.locator('#remaining').textContent(),'');assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
test('imported payments require an explicit date and do not count before confirmation',async()=>{
 const browser=await engine.launch();try{const {page,db}=await open(browser);await page.getByRole('button',{name:'Review payment',exact:true}).click();assert.equal(await page.locator('#date').inputValue(),'');await page.locator('#payment-submit').click();assert.equal(db.payments.length,0);await page.locator('#date').fill('2026-01-01');await page.locator('#payment-submit').click();await page.locator('#payment-dialog').waitFor({state:'hidden'});assert.equal(db.payments[0].sourcePayer,0);await page.getByText('Confirmed',{exact:true}).waitFor();}finally{await browser.close();}
});
test('signed-out and denied accounts see no private rent information',async()=>{
 const browser=await engine.launch();try{for(const mode of ['signed-out','denied']){const {page}=await open(browser,390,mode);await page.getByText(mode==='signed-out'?'Sign in form':'This account doesn’t have access to Rent. Sign out and use an approved email.',{exact:true}).waitFor();assert.equal(await page.locator('#app').isVisible(),false);assert.equal(await page.locator('#people').textContent(),'');await page.close();}}finally{await browser.close();}
});
test('an empty workspace can be initialized without importing financial history',async()=>{
 const browser=await engine.launch();try{const {page,db,errors}=await open(browser,390,'empty');await page.locator('#create').click();await page.locator('#rent-input').fill('3000');for(let i=0;i<3;i++){await page.locator(`#name-${i}`).fill(['Alex','Blair','Casey'][i]);await page.locator(`#room-${i}`).fill('100');}await page.locator('#config-submit').click();await page.locator('#config-dialog').waitFor({state:'hidden'});assert.equal(db.months.length,1);assert.equal(db.payments.length,0);assert.equal(await page.locator('#remaining').textContent(),'$3,000.00');assert.deepEqual(errors,[]);}finally{await browser.close();}
});
test('monthly cells support typing, keyboard navigation, pasting, batch save, and live charts',async()=>{
 const browser=await engine.launch();try{for(const width of [390,1280]){const {page,db,errors}=await open(browser,width);const month=db.months[0].month;
  const cell=field=>page.locator(`.rent-cell[data-month="${month}"][data-field="${field}"]`);
  await cell('p0').fill('1900');await cell('p0').press('Tab');assert.equal(await cell('p1').evaluate(n=>n===document.activeElement),true);
  await cell('p1').evaluate(n=>{const clipboardData=new DataTransfer();clipboardData.setData('text/plain','500\t400');n.dispatchEvent(new ClipboardEvent('paste',{clipboardData,bubbles:true,cancelable:true}));});
  assert.equal(await cell('p2').inputValue(),'400');assert.match(await page.locator('.year-summary').textContent(),/2,800/);assert.equal(await page.locator('.rent-trend svg').count(),1);assert.equal(await page.locator('.rent-split svg').count(),1);
  await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.locator('#rent-sheet .sheet-actions [role=status]').filter({hasText:'All changes saved'}).waitFor();assert.equal(db.payments.length,3);assert.equal(db.payments.reduce((s,p)=>s+p.amountCents,0),280000);
  assert.equal(await cell('p0').inputValue(),'1900.00');await page.screenshot({path:path.join(os.tmpdir(),`rent-sheet-${engine.name()}-${width}.png`),fullPage:true});
  const size=await page.evaluate(()=>[document.documentElement.scrollWidth,innerWidth]);assert.ok(size[0]<=size[1]);assert.deepEqual(errors,[]);await page.close();
 }}finally{await browser.close();}
});
test('grid retry keeps exact edits, refresh does not drop drafts, and sign-out erases the sheet',async()=>{
 const browser=await engine.launch();try{const {page,db}=await open(browser);const month=db.months[0].month;const input=page.locator(`.rent-cell[data-month="${month}"][data-field=p0]`);await input.fill('42.50');await page.locator('#refresh').click();assert.equal(await input.inputValue(),'42.50');db.fail=true;await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.locator('.sheet-error').filter({hasText:/retry safely/}).waitFor();assert.equal(await input.inputValue(),'42.50');db.fail=false;await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.locator('#rent-sheet .sheet-actions [role=status]').filter({hasText:'All changes saved'}).waitFor();assert.equal(db.payments.length,1);await page.locator('#sign-out').click();await page.getByText('Sign in form',{exact:true}).waitFor();assert.equal(await page.locator('.rent-cell').count(),0);assert.equal(await page.locator('.year-summary').textContent(),'');}finally{await browser.close();}
});

test('rent cells keep proof and individual checks together; utility ledger supports editing and PDFs',async()=>{
 const browser=await engine.launch();try{for(const width of [390,1280]){const {page,db,errors}=await open(browser,width);const m=db.months[0].month;
  // Save a received cell, then check and attach proof without using a separate library.
  const cell=page.locator(`.rent-cell[data-month="${m}"][data-field="p0"]`);await cell.fill('100');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.locator('#rent-sheet .sheet-actions [role=status]').first().filter({hasText:'All changes saved'}).waitFor();
  const td=cell.locator('..');assert.equal(await td.locator('input[type=checkbox]').count(),0);await td.getByRole('button').click();await page.locator('.record-dialog input[type=checkbox]').check();await page.locator('.record-dialog').getByText('✓ Checked',{exact:true}).waitFor();assert.equal(db.payments[0].checked,true);assert.equal(db.payments[0].amountCents,10000);
  await page.locator('.record-dialog').getByRole('button',{name:'+ Attach proof',exact:true}).click();await page.locator('#rent-upload').setInputFiles({name:'Synthetic proof.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a0t0AAAAASUVORK5CYII=','base64')});
  db.failUpload=true;await page.getByRole('button',{name:'Save attachment',exact:true}).click();await page.getByText(/Your file is kept here for retry/).waitFor();assert.equal(await page.locator('#rent-upload').evaluate(n=>n.files.length),1);db.failUpload=false;await page.getByRole('button',{name:'Save attachment',exact:true}).click();await page.getByRole('link',{name:'Download Synthetic proof.png'}).waitFor();assert.equal(db.files.length,1);assert.ok(await page.locator('.proof-preview').evaluate(n=>n.src.startsWith('blob:')));await page.locator('.record-dialog').getByRole('button',{name:'Close',exact:true}).click();assert.equal(await td.locator('.cell-proof.has-proof.is-checked').count(),1);const bounds=await td.evaluate(n=>{const a=n.getBoundingClientRect(),b=n.querySelector('button').getBoundingClientRect();return {height:a.height,top:b.top-a.top,right:a.right-b.right};});assert.ok(bounds.height<=51,JSON.stringify(bounds));assert.ok(bounds.top<=3&&bounds.right<=3,JSON.stringify(bounds));assert.equal(await page.getByText('Payment proof library',{exact:true}).count(),0);
  // Utility statement entry uses the same row/cell workflow, including rectangular paste.
  const bm=m.slice(0,4)+'-02',row=page.locator(`.utility-table tr[data-month="${bm}"]`),first=row.locator('[data-field=statementDate]');const yr=m.slice(0,4);
  await first.focus();
  await first.evaluate((n,text)=>{const data=new DataTransfer();data.setData('text',text);n.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}));},`${yr}-02-09\t${yr}-01-02\t${yr}-02-02\t${yr}-03-02\t300\t-50\t0`);
  assert.equal(await row.locator('.bill-total').textContent(),'250.00');db.failBills=true;await page.getByRole('button',{name:'Save statements',exact:true}).click();await page.locator('#rent-records .sheet-error').filter({hasText:/preserved/}).waitFor();db.failBills=false;await page.getByRole('button',{name:'Save statements',exact:true}).click();await page.locator('#rent-records [role=status]').filter({hasText:'All changes saved'}).waitFor();assert.equal(db.bills.length,1);assert.equal(db.bills[0].month,bm);assert.equal(db.bills[0].previousCents,-5000);
  await row.locator('[data-field=chargesCents]').fill('320');await page.getByRole('button',{name:'Save statements',exact:true}).click();await page.locator('#rent-records [role=status]').filter({hasText:'All changes saved'}).waitFor();assert.equal(db.bills.length,1);assert.equal(db.bills[0].totalCents,27000);assert.equal(db.payments.length,1);
  await row.getByRole('button',{name:'+ PDF',exact:true}).click();await page.getByRole('button',{name:'+ Attach PDF',exact:true}).click();await page.locator('#rent-upload').setInputFiles({name:'Statement.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 synthetic test')});await page.getByRole('button',{name:'Save attachment',exact:true}).click();await page.getByRole('link',{name:'Download Statement.pdf'}).waitFor();await page.locator('.record-dialog').getByRole('button',{name:'Close',exact:true}).click();assert.equal(await row.getByRole('button').textContent(),'▤ 1 PDF');
  await page.locator('#rent-sheet').screenshot({path:path.join(os.tmpdir(),`rent-integrated-${engine.name()}-${width}.png`)});await page.locator('#rent-records').screenshot({path:path.join(os.tmpdir(),`rent-utility-sheet-${engine.name()}-${width}.png`)});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
  await page.locator('#sign-out').click();await page.getByText('Sign in form',{exact:true}).waitFor();assert.equal(await page.locator('.record-dialog').textContent(),'');assert.equal(await page.locator('.bill-cell').evaluateAll(ns=>ns.some(n=>n.value!=='')),false);assert.equal(await page.locator('#app').isVisible(),false);await page.close();
 }}finally{await browser.close();}
});

test('corner proof keeps separate receipt checks inside; utility drafts survive refresh attempts',async()=>{
 const browser=await engine.launch();try{const {page,db,errors}=await open(browser),m=db.months[0].month;
 db.payments.push({_id:'first',month:m,payer:0,amountCents:10000,date:m+'-01',note:'First',createdAt:1,createdBy:'test'},{_id:'second',month:m,payer:0,amountCents:20000,date:m+'-02',note:'Second',createdAt:2,createdBy:'test'});
 await page.locator('#refresh').click();const td=page.locator(`.rent-cell[data-month="${m}"][data-field=p0]`).locator('..');await td.locator('.cell-proof').waitFor();assert.equal(await td.locator('input[type=checkbox]').count(),0);assert.equal(await td.locator('button').count(),1);await td.locator('button').click();assert.equal(await page.locator('.record-dialog input[type=checkbox]').count(),2);await page.locator('.record-dialog input[type=checkbox]').nth(0).check();await page.locator('.record-dialog').getByText('✓ Checked',{exact:true}).waitFor();assert.equal(db.payments[0].checked,true);assert.equal(db.payments[1].checked,undefined);await page.locator('.record-dialog').getByRole('button',{name:'Close',exact:true}).click();
 const c=page.locator(`.utility-table tr[data-month="${m}"] [data-field=chargesCents]`);await c.fill('125');await page.locator('#refresh').click();await page.locator('#notice').filter({hasText:/Save or discard/}).waitFor();assert.equal(await c.inputValue(),'125.00');await td.locator('button').click();assert.equal(await page.locator('.record-dialog').isVisible(),false);await page.locator('#rent-records').getByRole('button',{name:'Discard edits',exact:true}).click();assert.equal(await c.inputValue(),'');assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
test('chart breakdown supports hover, focus, tap, exact cents and independent overpayments',async()=>{
 const browser=await engine.launch();try{for(const width of [390,1280]){const {page,db,errors}=await open(browser,width),m=db.months[0].month;
 db.payments.push({_id:'a',month:m,payer:0,amountCents:250099,date:m+'-01',note:'Synthetic overpayment',createdAt:1,createdBy:'test',checked:true},{_id:'b',month:m,payer:1,amountCents:35000,date:m+'-02',note:'Partial',createdAt:2,createdBy:'test'});await page.locator('#refresh').click();await page.locator('.proof-checkmark').waitFor();assert.equal(await page.locator('.proof-checkmark').textContent(),'✓');
 const bar=page.locator(`.rent-month-bar[data-month="${m}"]`),tip=page.locator('#rent-month-tooltip');if(width<800)await bar.tap();else await bar.hover();await tip.waitFor();assert.match(await tip.textContent(),/2,850\.99/);assert.match(await tip.textContent(),/3,750\.00/);assert.match(await tip.textContent(),/Overpaid: Alex \$600\.99/);assert.match(await tip.locator('tbody tr').first().textContent(),/Alex\$1,900\.00\$2,500\.99\$0\.00/);assert.equal(await tip.locator('tbody tr').count(),4);
 const bounds=await tip.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width,JSON.stringify(bounds));if(width>=800){await tip.hover();assert.equal(await tip.isVisible(),true);}await page.locator('.coverage-card').screenshot({path:path.join(os.tmpdir(),`rent-hover-${engine.name()}-${width}.png`)});await page.screenshot({path:path.join(os.tmpdir(),`rent-hover-page-${engine.name()}-${width}.png`)});
 await page.keyboard.press('Escape');await tip.waitFor({state:'hidden'});await bar.evaluate(n=>n.blur());await bar.focus();await tip.waitFor();await page.keyboard.press('Escape');await tip.waitFor({state:'hidden'});await bar.click();await tip.waitFor();await page.locator('header h1').click();await tip.waitFor({state:'hidden'});
 const input=page.locator(`.rent-cell[data-month="${m}"][data-field=p1]`);await input.fill('351.25');await page.locator(`.rent-month-bar[data-month="${m}"]`).click();await tip.waitFor();assert.match(await tip.textContent(),/Unsaved preview/);assert.match(await tip.textContent(),/2,852\.24/);assert.deepEqual(errors,[]);
 await page.locator('#sign-out').click();await page.getByText('Sign in form',{exact:true}).waitFor();assert.equal(await page.locator('#rent-month-tooltip').count(),0);await page.close();
 }}finally{await browser.close();}
});

test('proof row flags persist per receipt, keep history and failed drafts, and clear on sign-out',async()=>{
 const browser=await engine.launch();try{for(const width of [390,1280]){const {page,db,errors}=await open(browser,width),m=db.months[0].month;
 const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1000;c.height=1400;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,1000,1400);x.fillStyle='#234';x.font='26px sans-serif';x.fillText('Synthetic payment history',50,90);for(let i=0;i<8;i++){x.fillStyle=i%2?'#f5f5ef':'#fff';x.fillRect(40,150+i*145,920,140);x.fillStyle='#345';x.fillText('Test transfer '+(i+1)+'     $100.00',60,210+i*145);}return c.toDataURL('image/png').split(',')[1];});db.proofBytes=Buffer.from(image,'base64');
 db.payments.push({_id:'flagged',month:m,payer:0,amountCents:10000,date:m+'-01',note:'Synthetic receipt',createdAt:1,createdBy:'test'},{_id:'other',month:m,payer:0,amountCents:20000,date:m+'-02',note:'Separate receipt',createdAt:2,createdBy:'test'});
 db.files.push({_id:'proof',name:'Synthetic history.png',type:'image/png',paymentIds:['flagged','other'],entries:[{paymentId:'flagged',date:m+'-01',status:'Completed',memo:'Rent'}]});
 await page.locator('#refresh').click();const cell=page.locator(`.rent-cell[data-month="${m}"][data-field=p0]`).locator('..');await cell.locator('button').click();
 const first=page.locator('.receipt-detail').first();await first.getByRole('button',{name:'Flag payment row',exact:true}).click();await first.getByRole('slider',{name:'Flag row position'}).fill('320');await first.getByRole('slider',{name:'Flag row height'}).fill('80');
 db.failMark=true;await first.getByRole('button',{name:'Save row flag',exact:true}).click();await first.getByRole('status').filter({hasText:/Couldn’t save/}).waitFor();assert.equal(await first.getByRole('slider',{name:'Flag row position'}).inputValue(),'320');assert.equal(db.marks.length,0);
 db.failMark=false;await first.getByRole('button',{name:'Save row flag',exact:true}).click();await first.getByRole('button',{name:'Adjust row flag',exact:true}).waitFor();assert.equal(db.marks.length,1);assert.equal(db.marks[0].paymentId,'flagged');assert.equal(db.marks[0].y,.32);assert.equal(db.payments[0].checked,undefined);
 const second=page.locator('.receipt-detail').nth(1);assert.equal(await second.locator('.proof-row-flag').isVisible(),false);assert.equal(await first.locator('.proof-row-flag').isVisible(),true);
 await first.locator('.proof-stage').scrollIntoViewIfNeeded();await page.locator('.record-dialog').screenshot({path:path.join(os.tmpdir(),`rent-proof-flags-${engine.name()}-${width}.png`)});
 const bounds=await first.locator('.proof-row-flag').boundingBox(),stage=await first.locator('.proof-stage').boundingBox();assert.ok(Math.abs(bounds.y-stage.y-stage.height*.32)<2);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await first.getByRole('button',{name:'Adjust row flag',exact:true}).click();await first.getByRole('button',{name:'Remove row flag',exact:true}).click();await first.getByRole('button',{name:'Flag payment row',exact:true}).waitFor();assert.equal(db.marks.length,2);assert.ok(db.marks[1].removed);await first.getByText('Flag history · 2 revisions',{exact:true}).click();assert.match(await first.locator('.proof-flag-history').textContent(),/test@example.com/);
 await first.getByRole('button',{name:'Flag payment row',exact:true}).click();await page.evaluate(()=>window.changeSession(null));await page.getByText('Sign in form',{exact:true}).waitFor();assert.equal(await page.locator('.proof-audit').count(),0);assert.deepEqual(errors,[]);await page.close();
 }}finally{await browser.close();}
});
