const {test,before}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),vm=require('node:vm'),esbuild=require('esbuild');
let api,http;
before(async()=>{async function bundle(file){const r=await esbuild.build({entryPoints:[path.join(__dirname,'../../../convex/'+file)],bundle:true,write:false,platform:'node',format:'cjs',plugins:[{name:'handlers',setup(b){b.onResolve({filter:/\.\/_generated\/server$/},()=>({path:'server',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const query=x=>x;export const mutation=x=>x;export const internalMutation=x=>x;export const httpAction=x=>x;'}));}}]});const m={exports:{}};vm.runInNewContext(r.outputFiles[0].text,{module:m,exports:m.exports,require,console,TextEncoder,TextDecoder,Response,Request,URL,Uint8Array});return m.exports;}api=await bundle('rentRecords.ts');http=await bundle('rentFileHttp.ts');});
function fixture(identity={email:'john@affil.ai',issuer:'https://clerk.john-ta.com'}){const tables={rentBills:[],rentPayments:[],rentFiles:[]},deleted=[];let n=0;const ctx={auth:{getUserIdentity:async()=>identity},storage:{delete:async id=>deleted.push(id)},db:{query(t){let filters=[];const q={withIndex(_,fn){fn({eq(k,v){filters.push(r=>r[k]===v);}});return q;},collect:async()=>tables[t].filter(r=>filters.every(f=>f(r))),async unique(){return (await q.collect())[0]||null;}};return q;},get:async id=>Object.values(tables).flat().find(r=>r._id===id),insert:async(t,v)=>{const _id='id'+n++;tables[t].push({...v,_id});return _id;},patch:async(id,v)=>Object.assign(await ctx.db.get(id),v)}};return {ctx,tables,deleted,run:(name,args={})=>api[name].handler(ctx,args)};}
const bill={statementDate:'2026-02-09',periodStart:'2026-01-02',periodEnd:'2026-02-02',dueDate:'2026-03-02',chargesCents:30000,previousCents:-5000,paymentsCents:0,totalCents:25000,note:'Synthetic statement',requestKey:'bill1'};
test('documents, checks and bills require the rent allowlist',async()=>{for(const id of [null,{email:'other@example.com',emailVerified:true},{email:'john@affil.ai',emailVerified:false}])for(const name of ['overview','file','destination','setConfirmation','saveBill','linkFile'])await assert.rejects(fixture(id).run(name,{}),/not authorized/);});
test('bills use statement month, retain cross-month dates and credits, reconcile and deduplicate',async()=>{const f=fixture(),id=await f.run('saveBill',bill);assert.equal(await f.run('saveBill',bill),id);assert.equal(f.tables.rentBills[0].month,'2026-02');assert.equal(f.tables.rentBills[0].previousCents,-5000);await assert.rejects(f.run('saveBill',{...bill,requestKey:'different'}),/already logged/);await assert.rejects(f.run('saveBill',{...bill,totalCents:10}),/must equal/);await assert.rejects(f.run('saveBill',{...bill,periodEnd:'2026-02-30'}),/valid dates/);await assert.rejects(f.run('saveBill',{...bill,periodStart:'2026-03-01'}),/Check the bill/);});
test('checking a receipt never changes amount; voided receipts cannot be checked',async()=>{const f=fixture();f.tables.rentPayments.push({_id:'p',amountCents:12345});await f.run('setConfirmation',{id:'p',checked:true});assert.equal(f.tables.rentPayments[0].checked,true);assert.equal(f.tables.rentPayments[0].amountCents,12345);await f.run('setConfirmation',{id:'p',checked:false});assert.equal(f.tables.rentPayments[0].checked,false);f.tables.rentPayments[0].voidedAt=1;await assert.rejects(f.run('setConfirmation',{id:'p',checked:true}),/not available/);});
test('uploads retain proof links and retries discard duplicate storage without creating another file',async()=>{const f=fixture();f.tables.rentPayments.push({_id:'p'});const a={paymentId:'p',storageId:'s1',name:'proof.png',type:'image/png',size:100,requestKey:'upload1',author:'test'};const id=await f.run('attach',a);assert.equal(await f.run('attach',{...a,storageId:'s2'}),id);assert.equal(f.tables.rentFiles.length,1);assert.deepEqual(f.deleted,['s2']);assert.equal(f.tables.rentPayments[0].checked,undefined);const overview=await f.run('overview');assert.equal(overview.files[0].storageId,undefined);});
test('evidence checks only unique exact matches and never adds receipts',async()=>{const f=fixture();f.tables.rentFiles.push({_id:'f',paymentIds:[]});f.tables.rentPayments.push({_id:'p',month:'2026-01',payer:0,amountCents:10000});const entries=[{date:'2026-01-01',month:'2026-01',payer:0,amountCents:10000,memo:'January rent',status:'Completed',review:''},{date:'2026-01-30',payer:0,amountCents:50000,memo:'Unknown transfer',status:'Completed',review:'Month unclear'},{date:'2026-02-01',month:'2026-02',payer:0,amountCents:10000,memo:'February',status:'Completed',review:''}];const result=await f.run('importEvidence',{id:'f',entries});assert.equal(result.linked,1);assert.equal(result.review,2);assert.equal(f.tables.rentPayments.length,1);assert.equal(f.tables.rentPayments[0].checked,true);await f.run('importEvidence',{id:'f',entries});assert.equal(f.tables.rentFiles[0].paymentIds.length,1);});
test('private file HTTP rejects anonymous access and invalid files before storage, serves authorized blobs',async()=>{const denied=await http.attachment(fixture(null).ctx,new Request('https://site/rent-file?id=f'));assert.equal(denied.status,403);const f=fixture();let stored=false;f.ctx.runQuery=async()=>({storageId:'s',type:'image/png'});f.ctx.storage.get=async()=>new Blob(['private']);f.ctx.storage.store=async()=>{stored=true;return 's';};const get=await http.attachment(f.ctx,new Request('https://site/rent-file?id=f'));assert.equal(await get.text(),'private');assert.equal(get.headers.get('Cache-Control'),'no-store');const bad=await http.attachment(f.ctx,new Request('https://site/rent-file',{method:'POST',headers:{'Content-Type':'image/png','X-Request-Key':'k'},body:'not an image'}));assert.equal(bad.status,400);assert.equal(stored,false);});

test('manual linking is idempotent and does not check or change receipts',async()=>{const f=fixture();f.tables.rentFiles.push({_id:'f',paymentIds:[]});f.tables.rentPayments.push({_id:'p',amountCents:10000});await f.run('linkFile',{id:'f',paymentId:'p'});await f.run('linkFile',{id:'f',paymentId:'p'});assert.equal(f.tables.rentFiles[0].paymentIds.length,1);assert.equal(f.tables.rentPayments[0].checked,undefined);});
